REBOL [
  Title:   "Generates Red/System integer! tests"
	Author:  "Peter W A Wood"
	File: 	 %make-integer-auto-test.r
	Version: 0.1.1
	Rights:  "Copyright (C) 2011 Peter W A Wood. All rights reserved."
	License: "BSD-3 - https://github.com/dockimbel/Red/blob/origin/BSD-3-License.txt"
]
rand: func [
  "returns a random number between -2147483647 and 2147483647"
  /local i
][
  i: random 2147483647
  if 2 = random 2 [i: - i]
  i
]

;; initialisations 
tests: copy ""                          ;; string to hold generated tests
test-number: 0                          ;; number of the generated test

;; create a block of values to be used in the binary ops tests
test-values: [
            0                   ; zero
  -2147483648                   ; min
   2147483647                   ; max
                                ;; DO NOT USE -1 as it crashes REBOL !!!!
            3
           -7
            5
       123456
]
loop 3 [append test-values rand]

;; create blocks of operators to be applied
test-binary-ops: [
  +
  -
  *
  /
  //
  or
  xor
  and
]

test-no-zeroes: [         ;; zero not allowed as operand2
  / 
  //
]

test-comparison-ops: [
  =
  <>
  <
  >
  >=
  =<
]

test-comparison-values: [
  -1
  0
  +1
]

;; create test file with header
append tests "Red/System [^/"
append tests {  Title:   "Red/System auto-generated integer! tests"^/}
append tests {	Author:  "Peter W A Wood"^/}
append tests {  File: 	 %integer-auto-test.reds^/}
append tests {  License: "BSD-3 - https://github.com/dockimbel/Red/blob/origin/BSD-3-License.txt"^/}
append tests "]^/^/"
append tests "^/^/comment {"
append tests "  This file is generated by make-integer-auto-test.r^/"
append tests "  Do not edit this file directly.^/"
append tests "}^/^/"
append tests "#include %../../quick-test/quick-test.reds^/^/"
append tests {~~~start-file~~~ "integer!"^/^/}
append tests {===start-group=== "Auto-generated tests for integers"^/^/}

write %integer-auto-test.reds tests
tests: copy ""

;; binary operator tests
foreach op test-binary-ops [
  foreach operand1 test-values [
    foreach operand2 test-values [
      ;; only write a test if REBOL produces a result
      if attempt [expected: do reduce [operand1 op operand2]][
        
        ;; don't write tests for certain ops with zero second operand
        if not all [
          operand2 = 0
          find test-no-zeroes op 
        ][
          expected: to-integer expected
          ;; test with literal values
          test-number: test-number + 1
          append tests join {  --test-- "integer-auto-} [test-number {"^/}]
          append tests "  --assert "
          append tests reform [expected " = (" operand1 op operand2 ")^/"]
          
          ;; test with variables
          test-number: test-number + 1
          append tests join {  --test-- "integer-auto-} [test-number {"^/}]
          append tests join "      i: " [operand1 "^/"]
          append tests join "      j: " [operand2 "^/"]
          append tests rejoin ["      k:  i " op " j^/"]
          append tests "  --assert "
          append tests reform [expected " = k ^/"]
          
          ;; test as local variables in a function
          test-number: test-number + 1
          func-name: join "f" :test-number
          append tests join {  --test-- "integer-auto-} [test-number {"^/}]
          append tests join "    " [func-name ": func [^/"]
          append tests "      return: [integer!]^/"
          append tests "      /local^/"
          append tests "      i [integer!]^/"
          append tests "      j [integer!]^/"
          append tests "      k [integer!]^/"
          append tests "    ][^/"
          append tests join "      i: " [operand1 "^/"]
          append tests join "      j: " [operand2 "^/"]
          append tests join "      k:  i " [op " j^/]^/"]
          append tests "  --assert "
          append tests join "" [expected " = " func-name "^/"]
          
          ;; write tests to file
          write/append %integer-auto-test.reds tests
          tests: copy ""
        ]
      ]
      recycle
    ]
  ]
]

;; comparison tests
foreach op test-comparison-ops [
  foreach operand1 test-values [
    foreach operand2 test-comparison-values [
      ;; only write a test if REBOL produces a result
      if all [
        attempt [operand2: operand1 + operand2]
        attempt [expected: do reduce [operand1 op operand2]]
      ][
        test-number: test-number + 1
        append tests join {  --test-- "integer-auto-} [test-number {"^/}]
        append tests "  --assert "
        append tests reform [expected " = (" operand1 op operand2 ")^/"]

        ;; write tests to file
        write/append %integer-auto-test.reds tests
        tests: copy ""
      ]
    ]
  ]
]

;; write file epilog
append tests "^/===end-group===^/^/"
append tests "~~~end-file~~~"

write/append %integer-auto-test.reds tests
      
print ["Number of assertions generated" test-number]






