Red []
	#include %../quick-test/quick-test.red
	***start-run*** "Testing Red Compiler"
	#include %source/units/logic-test.red
  	#include %source/units/conditional-test.red
  	#include %source/units/series-test.red
  	#include %source/units/path-test.red
  	#include %source/units/serialization-test.red
  	#include %source/units/function-test.red
  	#include %source/units/loop-test.red
  	#include %source/units/type-test.red
  	#include %source/units/find-test.red
  	#include %source/units/select-test.red
  	#include %source/units/binding-test.red
  	#include %source/units/evaluation-test.red
  	#include %source/units/load-test.red
  	#include %source/units/switch-test.red
  	#include %source/units/case-test.red
  	#include %source/units/routine-test.red
  	#include %source/units/append-test.red
  	#include %source/units/insert-test.red
  	#include %source/units/make-test.red
  	#include %source/units/system-test.red
  	#include %source/units/parse-test.red
  	#include %source/units/bitset-test.red
  	#include %source/units/strict-equal-test.red
  	#include %source/units/object-test.red
  	#include %source/units/auto-tests/integer-auto-test.red
  	#include %source/units/auto-tests/infix-equal-auto-test.red
  	#include %source/units/auto-tests/equal-auto-test.red
  	#include %source/units/auto-tests/infix-not-equal-auto-test.red
  	#include %source/units/auto-tests/not-equal-auto-test.red
  	#include %source/units/auto-tests/infix-lesser-auto-test.red
  	#include %source/units/auto-tests/lesser-auto-test.red
  	#include %source/units/auto-tests/infix-lesser-equal-auto-test.red
  	#include %source/units/auto-tests/lesser-equal-auto-test.red
  	#include %source/units/auto-tests/infix-greater-auto-test.red
  	#include %source/units/auto-tests/greater-auto-test.red
  	#include %source/units/auto-tests/infix-greater-equal-auto-test.red
  	#include %source/units/auto-tests/greater-equal-auto-test.red
  	***end-run***
