Red []
	#include %../quick-test/quick-test.red
	***start-run*** "Testing Red Interpreter"
	#include %source/units/auto-tests/interpreter-binding-test.red
  	#include %source/units/auto-tests/interpreter-case-test.red
  	#include %source/units/auto-tests/interpreter-conditional-test.red
  	#include %source/units/auto-tests/interpreter-evaluation-test.red
  	#include %source/units/auto-tests/interpreter-find-test.red
  	#include %source/units/auto-tests/interpreter-function-test.red
  	#include %source/units/auto-tests/interpreter-load-test.red
  	#include %source/units/auto-tests/interpreter-logic-test.red
  	#include %source/units/auto-tests/interpreter-loop-test.red
  	#include %source/units/auto-tests/interpreter-select-test.red
  	#include %source/units/auto-tests/interpreter-serialization-test.red
  	#include %source/units/auto-tests/interpreter-series-test.red
  	#include %source/units/auto-tests/interpreter-type-test.red
  	#include %source/units/auto-tests/interpreter-switch-test.red
  	#include %source/units/auto-tests/interpreter-append-test.red
  	#include %source/units/auto-tests/interpreter-insert-test.red
  	#include %source/units/auto-tests/interpreter-system-test.red
  	#include %source/units/auto-tests/interp-parse-test.red
  	#include %source/units/auto-tests/interp-bitset-test.red
  	#include %source/units/auto-tests/interp-equal-auto-test.red
  	#include %source/units/auto-tests/interp-greater-auto-test.red
  	#include %source/units/auto-tests/interp-inf-equal-auto-test.red
  	#include %source/units/auto-tests/interp-strict-equal-test.red
  	#include %source/units/auto-tests/interp-inf-greater-auto-test.red
  	#include %source/units/auto-tests/interp-inf-lesser-auto-test.red
  	#include %source/units/auto-tests/interp-inf-lesser-equal-auto-test.red
  	#include %source/units/auto-tests/interp-inf-not-equal-auto-test.red
  	#include %source/units/auto-tests/interp-integer-auto-test.red
  	#include %source/units/auto-tests/interp-lesser-auto-test.red
  	#include %source/units/auto-tests/interp-lesser-equal-auto-test.red
  	#include %source/units/auto-tests/interp-not-equal-auto-test.red
  	#include %source/units/auto-tests/interp-integer-test.red
  	***end-run***
