
Rebol [
	Title:   "Red auto-generated test runner"
	Author:  "Peter W A Wood"
	License: "BSD-3 - https://github.com/dockimbel/Red/blob/origin/BSD-3-License.txt"
]

comment {
	This file is generated by make-run-each-runner.r
	Do not edit this file directly.
}

--run-test-file-quiet %source/units/auto-tests/interp-logic-test.red
--run-test-file-quiet %source/units/auto-tests/interp-conditional-test.red
--run-test-file-quiet %source/units/auto-tests/interp-series-test.red
--run-test-file-quiet %source/units/auto-tests/interp-path-test.red
--run-test-file-quiet %source/units/auto-tests/interp-serialization-test.red
--run-test-file-quiet %source/units/auto-tests/interp-function-test.red
--run-test-file-quiet %source/units/auto-tests/interp-loop-test.red
--run-test-file-quiet %source/units/auto-tests/interp-type-test.red
--run-test-file-quiet %source/units/auto-tests/interp-find-test.red
--run-test-file-quiet %source/units/auto-tests/interp-select-test.red
--run-test-file-quiet %source/units/auto-tests/interp-binding-test.red
--run-test-file-quiet %source/units/auto-tests/interp-load-test.red
--run-test-file-quiet %source/units/auto-tests/interp-switch-test.red
--run-test-file-quiet %source/units/auto-tests/interp-case-test.red
--run-test-file-quiet %source/units/auto-tests/interp-char-test.red
--run-test-file-quiet %source/units/auto-tests/interp-append-test.red
--run-test-file-quiet %source/units/auto-tests/interp-insert-test.red
--run-test-file-quiet %source/units/auto-tests/interp-make-test.red
--run-test-file-quiet %source/units/auto-tests/interp-system-test.red
--run-test-file-quiet %source/units/auto-tests/interp-parse-test.red
--run-test-file-quiet %source/units/auto-tests/interp-bitset-test.red
--run-test-file-quiet %source/units/auto-tests/interp-strict-equal-test.red
--run-test-file-quiet %source/units/auto-tests/interp-object-test.red
--run-test-file-quiet %source/units/auto-tests/interp-integer-test.red
--run-test-file-quiet %source/units/auto-tests/interp-float-test.red
--run-test-file-quiet %source/units/auto-tests/interp-same-test.red
--run-test-file-quiet %source/units/auto-tests/interp-integer-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-float-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-infix-equal-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-equal-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-infix-not-equal-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-not-equal-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-infix-lesser-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-lesser-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-infix-lesser-equal-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-lesser-equal-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-infix-greater-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-greater-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-infix-greater-equal-auto-test.red
--run-test-file-quiet %source/units/auto-tests/interp-greater-equal-auto-test.red
