Red/System [
	Title:	"Text Box Windows Uniscribe Backend"
	Author: "Xie Qingtian"
	File: 	%text-box.reds
	Tabs: 	4
	Rights: "Copyright (C) 2016 Xie Qingtian. All rights reserved."
	License: {
		Distributed under the Boost Software License, Version 1.0.
		See https://github.com/red/red/blob/master/BSL-License.txt
	}
]

#import [
	"usp10.dll" stdcall [
		ScriptGetCMap: "ScriptGetCMap" [
			hdc			[handle!]
			psc			[int-ptr!]
			text		[c-string!]
			len			[integer!]
			flags		[integer!]
			glyphs		[int-ptr!]
			return:		[integer!]
		]
		ScriptTextOut: "ScriptTextOut" [
			hdc			[handle!]
			psc			[int-ptr!]
			x			[integer!]
			y			[integer!]
			options		[integer!]
			lprc		[RECT_STRUCT]
			psa			[int-ptr!]
			pwcReserved [byte-ptr!]
			iReserved	[integer!]
			pwGlyphs	[int-ptr!]
			cGlyphs		[integer!]
			piAdvance	[int-ptr!]
			piJustify	[int-ptr!]
			pGoffset	[int-ptr!]
			return:		[integer!]
		]
		ScriptGetLogicalWidths: "ScriptGetLogicalWidths" [
			psa			[integer!]
			cChars		[integer!]
			cGlyphs		[integer!]
			pGlyphWidth [integer!]
			pwLogClust	[integer!]
			psva		[integer!]
			piDx		[integer!]
			return:		[integer!]
		]
		ScriptCPtoX: "ScriptCPtoX" [
			iCP			[integer!]
			fTrailing	[integer!]
			cChars		[integer!]
			cGlyphs		[integer!]
			pwLogClust	[int-ptr!]
			psva		[int-ptr!]
			piAdvance	[int-ptr!]
			psa			[int-ptr!]
			piX			[int-ptr!]
			return:		[integer!]
		]
		ScriptXtoCP: "ScriptXtoCP" [
			iX			[integer!]
			cChars		[integer!]
			cGlyphs		[integer!]
			pwLogClust	[int-ptr!]
			psva		[int-ptr!]
			piAdvance	[int-ptr!]
			psa			[int-ptr!]
			piCP		[int-ptr!]
			piTrailing	[int-ptr!]
			return:		[integer!]
		]
		ScriptBreak: "ScriptBreak" [
			pwcChars	[c-string!]
			cChars		[integer!]
			psa			[int-ptr!]
			psla		[int-ptr!]
			return:		[integer!]
		]
		ScriptItemize: "ScriptItemize" [
			pwcInChars	[c-string!]
			cInChars	[integer!]
			cMaxItems	[integer!]
			psControl	[int-ptr!]
			psState		[int-ptr!]
			pItems		[int-ptr!]
			pcItems		[int-ptr!]
			return:		[integer!]
		]
		ScriptLayout: "ScriptLayout" [
			cRuns		[integer!]
			pbLevel		[byte-ptr!]
			piVtoL		[int-ptr!]
			piLtoV		[int-ptr!]
			return:		[integer!]
		]
		ScriptShape: "ScriptShape" [
			hdc			[handle!]
			psc			[int-ptr!]
			pwcChars	[c-string!]
			cChars		[integer!]
			cMaxGlyphs	[integer!]
			psa			[int-ptr!]
			pwOutGlyphs [int-ptr!]
			pwLogClust	[int-ptr!]
			psva		[int-ptr!]
			pcGlyphs	[int-ptr!]
			return:		[integer!]
		]
		ScriptPlace: "ScriptPlace" [
			hdc			[handle!]
			psc			[int-ptr!]
			pwGlyphs	[int-ptr!]
			cGlyphs		[integer!]
			psva		[int-ptr!]
			psa			[int-ptr!]
			piAdvance	[int-ptr!]
			pGoffset	[int-ptr!]
			pABC		[int-ptr!]
			return:		[integer!]
		]
		;ScriptJustify: "ScriptJustify" []
		ScriptFreeCache: "ScriptFreeCache" [
			psc			[int-ptr!]
			return:		[integer!]
		]
		ScriptGetFontProperties: "ScriptGetFontProperties" [
			hdc			[handle!]
			psc			[int-ptr!]
			sfp			[int-ptr!]
			return:		[integer!]
		]
		ScriptStringAnalyse: "ScriptStringAnalyse" [
			hdc			[integer!]
			pString		[integer!]
			cString		[integer!]
			cGlyphs		[integer!]
			iCharset	[integer!]
			dwFlags		[integer!]
			iReqWidth	[integer!]
			psControl	[integer!]
			psState		[integer!]
			piDx		[integer!]
			pTabdef		[integer!]
			pbInClass	[integer!]
			pssa		[integer!]
			return:		[integer!]
		]
		ScriptStringOut: "ScriptStringOut" [
			ssa			[integer!]
			iX			[integer!]
			iY			[integer!]
			uOptions	[integer!]
			*prc		[RECT_STRUCT]
			iMinSel		[integer!]
			iMaxSel		[integer!]
			fDisabled	[logic!]
			return:		[integer!]
		]
		ScriptStringFree: "ScriptStringFree" [
			pssa		[int-ptr!]
			return:		[integer!]
		]
	]
]