Red [
  Title:   "Red auto-generated interpreter test"
	Author:  "Peter W A Wood"
  License: "BSD-3 - https://github.com/dockimbel/Red/blob/origin/BSD-3-License.txt"
]



comment {  This file is generated by make-interpreter-auto-test.r
  Do not edit this file directly.
}

#include %/C/Users/Old Man/Desktop/My Changes/quick-test/quick-test.red
 do [

~~~start-file~~~ "interp-make"

===start-group=== "make basic"
	
	--test-- "mb1 - issue #465"
		mb1-s: make string! 0
		append mb1-s #"B"
		append mb1-s #"C"
		append mb1-s #"D"
	--assert "BCD" = mb1-s
	
	--test-- "mb2"
		mb2-s: make string! 1 
		append mb2-s #"A"
		append mb2-s #"B"
		append mb2-s #"C"
		append mb2-s #"D"
	--assert "ABCD" = mb2-s
  
===end-group===

~~~end-file~~~

]