Red [
  Title:   "Red auto-generated interpreter test"
	Author:  "Peter W A Wood"
  License: "BSD-3 - https://github.com/dockimbel/Red/blob/origin/BSD-3-License.txt"
]



comment {  This file is generated by make-interpreter-auto-test.r
  Do not edit this file directly.
}

#include %/C/Users/Old Man/Desktop/My Changes/quick-test/quick-test.red
 do [

~~~start-file~~~ "interp-system"

===start-group=== "system word tests"

	--test-- "swt1 issue #455"
	--assert  function! = type? get first find words-of system/words 'file?
	
	--test-- "swt2 issue #455"
	--assert char! = type? get first find words-of system/words 'cr
	
	--test-- "swt3 issue #455"
	--assert action! = type? get first find words-of system/words 'find
	
	--test-- "swt4 issue #455"
	--assert datatype! = type? get first find words-of system/words 'function!
		
===end-group===

~~~end-file~~~

]