Red [
  Title:   "Red auto-generated interpreter test"
	Author:  "Peter W A Wood"
  License: "BSD-3 - https://github.com/dockimbel/Red/blob/origin/BSD-3-License.txt"
]



comment {  This file is generated by make-interpreter-auto-test.r
  Do not edit this file directly.
}

#include %/C/Users/Old Man/Desktop/My Changes/quick-test/quick-test.red
 do [

~~~start-file~~~ "interp-words-of"

===start-group=== "words-of-basic"

	--test-- "wob1"
		wob1-o: make object! [
		    b: [a b c d]
		    c: #"a"
		    f: 1.0
		    o: make object! [a: 1 b: 2 c: 3]
		    i: 1
		    n: none
		    s: "abcde"
		]
		--assert [b c f o i n s] = words-of wob1-o
	
===end-group===

===start-group=== "words-of-self"

	--test-- "wos1"
		wos1-o: make object! [
		    b: [a b c d]
		    c: #"a"
		    f: 1.0
		    o: make object! [a: 1 b: 2 c: 3]
		    i: 1
		    n: none
		    s: "abcde"
		    wos: words-of self
		]
		--assert [b c f o i n s wos] = wos1-o/wos
		
	--test-- "wos2"
		wos2-o: make object! [
		    b: [a b c d]
		    c: #"a"
		    f: 1.0
		    o: make object! [a: 1 b: 2 c: 3]
		    i: 1
		    n: none
		    s: "abcde"
		    do-wos: does [words-of self]
		]
		--assert [b c f o i n s do-wos] = wos2-o/do-wos
	
===end-group===

~~~end-file~~~]