Rebol [
  Title:   "Red auto-generated lexer rebol-tests"
	Author:  "Peter W A Wood"
  File: 	 %lexer-auto-test.r
  License: "BSD-3 - https://github.com/dockimbel/Red/blob/origin/BSD-3-License.txt"
]



comment {  This file is generated by make-lexer-auto-rebol-tests.r
  Do not edit this file directly.
}

do %../../../../lexer.r
do %../../../../quick-test/quick-unit-test.r

~~~start-file~~~ "lexer-auto"

===start-group=== "Delimiter Lexer tests"

	--test-- "lexer-delimiter-1"  --assert [[] ""]			= lexer/process {Red []""}
	--test-- "lexer-delimiter-2"  --assert [[] ""]			= lexer/process "Red []{}"
	--test-- "lexer-delimiter-3"  --assert [[] "{"]		= lexer/process {Red []"^{"}
	--test-- "lexer-delimiter-4"  --assert [[] "}"]		= lexer/process {Red []"^}"}
	--test-- "lexer-delimiter-5"  --assert [[] "{}"]		= lexer/process {Red []"^{^}"}
	--test-- "lexer-delimiter-6"  --assert [[] {^}^{}]		= lexer/process {Red []"^}^{"}
	--test-- "lexer-delimiter-7"  --assert [[] "^{^}^}"]	= lexer/process {Red []"^{^}^}"}
	--test-- "lexer-delimiter-8"  --assert [[] ""]			= lexer/process {Red []"^"}
	--test-- "lexer-delimiter-9"  --assert [[] ""]			= lexer/process "Red []{}"
	--test-- "lexer-delimiter-10" --assert [[] "{"]		= lexer/process "Red []{^^{}"
	--test-- "lexer-delimiter-11" --assert [[] {"}]		= lexer/process {Red []{"}}
	--test-- "lexer-delimiter-12" --assert [[] "^/"]		= lexer/process "Red []{^/}^/"
	--test-- "lexer-delimiter-13" --assert [[] "^/"]		= lexer/process "Red []{^/}"
	--test-- "lexer-delimiter-14" --assert [[] "^/"]		= lexer/process "Red []{^/}"
	--test-- "lexer-delimiter-15" --assert [[] {{"x"}}]	= lexer/process {Red []{{"x"}}}
	--test-- "lexer-delimiter-16" --assert [[] "{x}"]		= lexer/process {Red []"{x}"}
	--test-- "lexer-delimiter-17" --assert [[] {"x"}]		= lexer/process {Red []{"x"}}
	--test-- "lexer-delimiter-18" --assert [[] "x"]		= lexer/process {Red []{x}}
	
===end-group===

===start-group=== "lexer-time"

;	--test-- "lexer-time-1" --assert [[] 2147483645:59:59]	= lexer/process {Red []2147483645:59:59}

===end-group===

~~~end-file~~~
