
Red [
	Title:   "Red auto-generated test"
	Author:  "Peter W A Wood"
	License: "BSD-3 - https://github.com/dockimbel/Red/blob/origin/BSD-3-License.txt"
]

comment {
	This file is generated by make-run-all-red.r
	Do not edit this file directly.
}

#include %../../../../quick-test/quick-test.red

~~~start-file~~~ "run-all-comp2"
#include %run-all/logic-test.red
#include %run-all/series-test.red
#include %run-all/serialization-test.red
#include %run-all/loop-test.red
#include %run-all/find-test.red
#include %run-all/binding-test.red
#include %run-all/load-test.red
#include %run-all/case-test.red
#include %run-all/comparison-test.red
#include %run-all/append-test.red
#include %run-all/move-test.red
#include %run-all/system-test.red
#include %run-all/bitset-test.red
#include %run-all/object-test.red
#include %run-all/float-test.red
#include %run-all/words-of-test.red
#include %run-all/throw-test.red
#include %run-all/map-test.red
#include %run-all/convert-test.red
#include %run-all/reactivity-test.red
~~~end-file~~~
