
Rebol [
	Title:   "Red auto-generated test runner"
	Author:  "Peter W A Wood"
	License: "BSD-3 - https://github.com/dockimbel/Red/blob/origin/BSD-3-License.txt"
]

comment {
	This file is generated by make-run-each-runner.r
	Do not edit this file directly.
}

--run-test-file-quiet %source/units/preprocessor-test.red
--run-test-file-quiet %source/units/logic-test.red
--run-test-file-quiet %source/units/conditional-test.red
--run-test-file-quiet %source/units/series-test.red
--run-test-file-quiet %source/units/path-test.red
--run-test-file-quiet %source/units/serialization-test.red
--run-test-file-quiet %source/units/function-test.red
--run-test-file-quiet %source/units/loop-test.red
--run-test-file-quiet %source/units/type-test.red
--run-test-file-quiet %source/units/find-test.red
--run-test-file-quiet %source/units/select-test.red
--run-test-file-quiet %source/units/binding-test.red
--run-test-file-quiet %source/units/evaluation-test.red
--run-test-file-quiet %source/units/load-test.red
--run-test-file-quiet %source/units/switch-test.red
--run-test-file-quiet %source/units/case-test.red
--run-test-file-quiet %source/units/char-test.red
--run-test-file-quiet %source/units/comparison-test.red
--run-test-file-quiet %source/units/routine-test.red
--run-test-file-quiet %source/units/append-test.red
--run-test-file-quiet %source/units/insert-test.red
--run-test-file-quiet %source/units/move-test.red
--run-test-file-quiet %source/units/make-test.red
--run-test-file-quiet %source/units/system-test.red
--run-test-file-quiet %source/units/parse-test.red
--run-test-file-quiet %source/units/bitset-test.red
--run-test-file-quiet %source/units/strict-equal-test.red
--run-test-file-quiet %source/units/object-test.red
--run-test-file-quiet %source/units/integer-test.red
--run-test-file-quiet %source/units/float-test.red
--run-test-file-quiet %source/units/same-test.red
--run-test-file-quiet %source/units/words-of-test.red
--run-test-file-quiet %source/units/case-folding-test.red
--run-test-file-quiet %source/units/throw-test.red
--run-test-file-quiet %source/units/vector-test.red
--run-test-file-quiet %source/units/map-test.red
--run-test-file-quiet %source/units/pair-test.red
--run-test-file-quiet %source/units/convert-test.red
--run-test-file-quiet %source/units/checksum-test.red
--run-test-file-quiet %source/units/reactivity-test.red
--run-test-file-quiet %source/units/auto-tests/lexer-auto-test.red
