REBOL [
	Title: "macOS libSystem exports (i386) -- functions + data, all bound via /usr/lib/libSystem.B.dylib"
	File: %mac-libsystem.r
	Tabs: 4
]

mac-libsystem: context [
	functions: [
		{Block_size} {ConvertHeaderBytes} {DNSServiceAddRecord} {DNSServiceBrowse} {DNSServiceBrowserCreate} {DNSServiceBrowserCreate_rpc}
		{DNSServiceConstructFullName} {DNSServiceCreateConnection} {DNSServiceCreateDelegateConnection} {DNSServiceDiscoveryDeallocate} {DNSServiceDiscoveryMachPort} {DNSServiceDiscoveryReply_server}
		{DNSServiceDiscoveryReply_server_routine} {DNSServiceDiscovery_handleReply} {DNSServiceDomainEnumerationCreate} {DNSServiceDomainEnumerationCreate_rpc} {DNSServiceEnumerateDomains} {DNSServiceGetAddrInfo}
		{DNSServiceGetPID} {DNSServiceGetProperty} {DNSServiceNATPortMappingCreate} {DNSServiceProcessResult} {DNSServiceQueryRecord} {DNSServiceReconfirmRecord}
		{DNSServiceRefDeallocate} {DNSServiceRefSockFD} {DNSServiceRegister} {DNSServiceRegisterRecord} {DNSServiceRegistrationAddRecord} {DNSServiceRegistrationAddRecord_rpc}
		{DNSServiceRegistrationCreate} {DNSServiceRegistrationCreate_rpc} {DNSServiceRegistrationRemoveRecord} {DNSServiceRegistrationRemoveRecord_rpc} {DNSServiceRegistrationUpdateRecord} {DNSServiceRegistrationUpdateRecord_rpc}
		{DNSServiceRemoveRecord} {DNSServiceResolve} {DNSServiceResolverResolve} {DNSServiceResolverResolve_rpc} {DNSServiceSetDefaultDomainForUser} {DNSServiceSetDispatchQueue}
		{DNSServiceSleepKeepalive} {DNSServiceUpdateRecord} {LI_get_thread_item} {LI_get_thread_list} {LI_ils_create} {LI_set_thread_item}
		{LI_set_thread_list} {MKGetTimeBaseInfo} {NSGetNextSearchPathEnumeration} {NSStartSearchPathEnumeration} {OSAtomicAdd32} {OSAtomicAdd32Barrier}
		{OSAtomicAdd64} {OSAtomicAdd64Barrier} {OSAtomicAnd32} {OSAtomicAnd32Barrier} {OSAtomicAnd32Orig} {OSAtomicAnd32OrigBarrier}
		{OSAtomicCompareAndSwap32} {OSAtomicCompareAndSwap32Barrier} {OSAtomicCompareAndSwap64} {OSAtomicCompareAndSwap64Barrier} {OSAtomicCompareAndSwapInt} {OSAtomicCompareAndSwapIntBarrier}
		{OSAtomicCompareAndSwapLong} {OSAtomicCompareAndSwapLongBarrier} {OSAtomicCompareAndSwapPtr} {OSAtomicCompareAndSwapPtrBarrier} {OSAtomicDequeue} {OSAtomicEnqueue}
		{OSAtomicFifoDequeue} {OSAtomicFifoEnqueue} {OSAtomicOr32} {OSAtomicOr32Barrier} {OSAtomicOr32Orig} {OSAtomicOr32OrigBarrier}
		{OSAtomicTestAndClear} {OSAtomicTestAndClearBarrier} {OSAtomicTestAndSet} {OSAtomicTestAndSetBarrier} {OSAtomicXor32} {OSAtomicXor32Barrier}
		{OSAtomicXor32Orig} {OSAtomicXor32OrigBarrier} {OSMemoryBarrier} {OSSpinLockLock} {OSSpinLockTry} {OSSpinLockUnlock}
		{PeerConnectionRelease} {TXTRecordContainsKey} {TXTRecordCreate} {TXTRecordDeallocate} {TXTRecordGetBytesPtr} {TXTRecordGetCount}
		{TXTRecordGetItemAtIndex} {TXTRecordGetLength} {TXTRecordGetValuePtr} {TXTRecordRemoveValue} {TXTRecordSetValue} {_Block_copy}
		{_Block_copy_collectable} {_Block_extended_layout} {_Block_has_signature} {_Block_isDeallocating} {_Block_layout} {_Block_object_assign}
		{_Block_object_dispose} {_Block_release} {_Block_signature} {_Block_tryRetain} {_Block_use_GC} {_Block_use_GC5}
		{_Block_use_RR} {_Block_use_RR2} {_Block_use_stret} {_Exit} {_NSGetArgc} {_NSGetArgv}
		{_NSGetEnviron} {_NSGetMachExecuteHeader} {_NSGetProgname} {_NSSetProgramVars} {_Read_RuneMagi} {_Unwind_Backtrace}
		{_Unwind_DeleteException} {_Unwind_FindEnclosingFunction} {_Unwind_Find_FDE} {_Unwind_ForcedUnwind} {_Unwind_GetCFA} {_Unwind_GetDataRelBase}
		{_Unwind_GetGR} {_Unwind_GetIP} {_Unwind_GetIPInfo} {_Unwind_GetLanguageSpecificData} {_Unwind_GetRegionStart} {_Unwind_GetTextRelBase}
		{_Unwind_RaiseException} {_Unwind_Resume} {_Unwind_Resume_or_Rethrow} {_Unwind_SetGR} {_Unwind_SetIP} {__Balloc_D2A}
		{__Bfree_D2A} {__ULtod_D2A} {____old_semwait_signal_nocancel} {____sigwait_nocancel} {___mb_cur_max} {___mb_cur_max_l}
		{___runetype} {___runetype_l} {___tolower} {___tolower_l} {___toupper} {___toupper_l}
		{__absvdi2} {__absvsi2} {__accept} {__accept_nocancel} {__access_extended} {__add_ovflpage}
		{__addel} {__addvdi3} {__addvsi3} {__aio_suspend} {__aio_suspend_nocancel} {__any_on_D2A}
		{__ashldi3} {__ashrdi3} {__assert_rtn} {__atomic_compare_exchange} {__atomic_compare_exchange_1} {__atomic_compare_exchange_2}
		{__atomic_compare_exchange_4} {__atomic_compare_exchange_8} {__atomic_exchange} {__atomic_exchange_1} {__atomic_exchange_2} {__atomic_exchange_4}
		{__atomic_exchange_8} {__atomic_fetch_add_1} {__atomic_fetch_add_2} {__atomic_fetch_add_4} {__atomic_fetch_add_8} {__atomic_fetch_and_1}
		{__atomic_fetch_and_2} {__atomic_fetch_and_4} {__atomic_fetch_and_8} {__atomic_fetch_or_1} {__atomic_fetch_or_2} {__atomic_fetch_or_4}
		{__atomic_fetch_or_8} {__atomic_fetch_sub_1} {__atomic_fetch_sub_2} {__atomic_fetch_sub_4} {__atomic_fetch_sub_8} {__atomic_fetch_xor_1}
		{__atomic_fetch_xor_2} {__atomic_fetch_xor_4} {__atomic_fetch_xor_8} {__atomic_load} {__atomic_load_1} {__atomic_load_2}
		{__atomic_load_4} {__atomic_load_8} {__atomic_store} {__atomic_store_1} {__atomic_store_2} {__atomic_store_4}
		{__atomic_store_8} {__b2d_D2A} {__big_delete} {__big_insert} {__big_keydata} {__big_return}
		{__big_split} {__bind} {__bsdthread_create} {__bsdthread_register} {__bsdthread_terminate} {__bt_close}
		{__bt_cmp} {__bt_defcmp} {__bt_defpfx} {__bt_delete} {__bt_dleaf} {__bt_fd}
		{__bt_free} {__bt_get} {__bt_new} {__bt_open} {__bt_pgin} {__bt_pgout}
		{__bt_put} {__bt_ret} {__bt_search} {__bt_seq} {__bt_setcur} {__bt_split}
		{__bt_sync} {__buf_free} {__bzero} {__call_hash} {__carbon_delete} {__chmod}
		{__chmod_extended} {__chud} {__clear_cache} {__close} {__close_nocancel} {__clzdi2}
		{__clzsi2} {__cmp_D2A} {__cmpdi2} {__collate_equiv_match} {__collate_lookup} {__commpage_gettimeofday}
		{__connect} {__connect_nocancel} {__copybits_D2A} {__copyfile} {__cospi} {__cospif}
		{__ctzdi2} {__ctzsi2} {__cxa_atexit} {__cxa_finalize} {__cxa_thread_atexit} {__d2b_D2A}
		{__dbpanic} {__decrement_D2A} {__default_utx} {__delete} {__delpair} {__deregister_frame}
		{__deregister_frame_info} {__deregister_frame_info_bases} {__diff_D2A} {__dirhelper_create_user_local} {__dirhelper_idle_exit} {__disable_threadsignal}
		{__disk_stack_logging_log_stack} {__divdc3} {__divdi3} {__divsc3} {__divxc3} {__dn_skipname}
		{__dtoa} {__enable_execute_stack} {__error} {__exit} {__exp10} {__exp10f}
		{__expand_table} {__fchmod} {__fchmod_extended} {__fcntl} {__fcntl_nocancel} {__fdnlist}
		{__fegetfltrounds} {__fflush} {__ffsdi2} {__fgetwc} {__find_bigpair} {__find_last_page}
		{__fix_locale_grouping_str} {__fixdfdi} {__fixsfdi} {__fixunsdfdi} {__fixunsdfsi} {__fixunssfdi}
		{__fixunssfsi} {__fixunsxfdi} {__fixunsxfsi} {__fixxfdi} {__floatdidf} {__floatdisf}
		{__floatdixf} {__floatundidf} {__floatundisf} {__floatundixf} {__fork} {__fpclassify}
		{__fpclassifyd} {__fpclassifyf} {__fpclassifyl} {__fread} {__free_ovflpage} {__freedtoa}
		{__fsgetpath} {__fstat64_extended} {__fstat_extended} {__fsync} {__fsync_nocancel} {__gcc_personality_v0}
		{__gdtoa} {__get_buf} {__get_page} {__get_remove_counter} {__getattrlist} {__getdirentries64}
		{__gethex_D2A} {__gethostuuid} {__getlcid} {__getlogin} {__getonlyClocaleconv} {__getpeername}
		{__getpid} {__getrlimit} {__getsgroups} {__getsockname} {__gettid} {__gettimeofday}
		{__getwgroups} {__guarded_open_np} {__hash_open} {__hdtoa} {__hexdig_init_D2A} {__hexnan_D2A}
		{__hi0bits_D2A} {__hldtoa} {__i2b_D2A} {__ibitmap} {__identitysvc} {__inc_remove_counter}
		{__increment_D2A} {__inf} {__inff} {__infl} {__initgroups} {__inline_isfinited}
		{__inline_isfinitef} {__inline_isfinitel} {__inline_isinfd} {__inline_isinff} {__inline_isinfl} {__inline_isnand}
		{__inline_isnanf} {__inline_isnanl} {__inline_isnormald} {__inline_isnormalf} {__inline_isnormall} {__inline_signbitd}
		{__inline_signbitf} {__inline_signbitl} {__ioctl} {__iopolicysys} {__isctype} {__isfinite}
		{__isfinited} {__isfinitef} {__isfinitel} {__isinf} {__isinfd} {__isinff}
		{__isinfl} {__isnan} {__isnand} {__isnanf} {__isnanl} {__isnormal}
		{__isnormald} {__isnormalf} {__isnormall} {__istype} {__istype_l} {__ivaliduser}
		{__ivaliduser_af} {__ivaliduser_sa} {__kdebug_trace} {__keymgr_dwarf2_register_sections} {__keymgr_initializer} {__kill}
		{__lchown} {__ldtoa} {__libc_init} {__libkernel_init} {__libplatform_init} {__listen}
		{__lo0bits_D2A} {__log2} {__lseek} {__lshift_D2A} {__lshrdi3} {__lstat64_extended}
		{__lstat_extended} {__mac_execve} {__mac_get_fd} {__mac_get_file} {__mac_get_lcid} {__mac_get_lctx}
		{__mac_get_link} {__mac_get_mount} {__mac_get_pid} {__mac_get_proc} {__mac_getfsstat} {__mac_mount}
		{__mac_set_fd} {__mac_set_file} {__mac_set_lctx} {__mac_set_link} {__mac_set_proc} {__mac_syscall}
		{__mach_stack_logging_enumerate_records} {__mach_stack_logging_frames_for_uniqued_stack} {__mach_stack_logging_get_frames} {__mach_stack_logging_set_file_path} {__malloc_entropy_setup} {__malloc_init}
		{__maskrune} {__maskrune_l} {__match_D2A} {__math_errhandling} {__memccpy_chk} {__memcpy_chk}
		{__memmove_chk} {__memset_chk} {__mkdir_extended} {__mkfifo_extended} {__mmap} {__moddi3}
		{__mprotect} {__msgctl} {__msgrcv} {__msgrcv_nocancel} {__msgsnd} {__msgsnd_nocancel}
		{__msgsys} {__msync} {__msync_nocancel} {__muldc3} {__muldi3} {__mulodi4}
		{__mulosi4} {__mulsc3} {__mult_D2A} {__multadd_D2A} {__mulvdi3} {__mulvsi3}
		{__mulxc3} {__munmap} {__nan} {__negdi2} {__negvdi2} {__negvsi2}
		{__nrv_alloc_D2A} {__old_semwait_signal} {__open} {__open_dprotected_np} {__open_extended} {__open_nocancel}
		{__opendir2} {__opendir2$INODE64$UNIX2003} {__opendir2$UNIX2003} {__os_once_reset} {__ovfl_delete} {__ovfl_get}
		{__ovfl_put} {__paritydi2} {__paritysi2} {__pipe} {__poll} {__poll_nocancel}
		{__popcountdi2} {__popcountsi2} {__posix_spawn} {__pow5mult_D2A} {__powidf2} {__powisf2}
		{__powixf2} {__pread} {__pread_nocancel} {__proc_info} {__process_policy} {__psynch_cvbroad}
		{__psynch_cvclrprepost} {__psynch_cvsignal} {__psynch_cvwait} {__psynch_mutexdrop} {__psynch_mutexwait} {__psynch_rw_downgrade}
		{__psynch_rw_longrdlock} {__psynch_rw_rdlock} {__psynch_rw_unlock} {__psynch_rw_unlock2} {__psynch_rw_upgrade} {__psynch_rw_wrlock}
		{__psynch_rw_yieldwrlock} {__pthread_canceled} {__pthread_chdir} {__pthread_fchdir} {__pthread_init} {__pthread_kill}
		{__pthread_markcancel} {__pthread_set_self} {__pthread_sigmask} {__pthread_workqueue_setkill} {__ptrace} {__put_page}
		{__pwrite} {__pwrite_nocancel} {__quorem_D2A} {__ratio_D2A} {__read} {__read_nocancel}
		{__readv} {__readv_nocancel} {__rec_close} {__rec_delete} {__rec_dleaf} {__rec_fd}
		{__rec_fmap} {__rec_fpipe} {__rec_get} {__rec_iput} {__rec_open} {__rec_put}
		{__rec_ret} {__rec_search} {__rec_seq} {__rec_sync} {__rec_vmap} {__rec_vpipe}
		{__reclaim_buf} {__recvfrom} {__recvfrom_nocancel} {__recvmsg} {__recvmsg_nocancel} {__register_frame}
		{__register_frame_info} {__register_frame_info_bases} {__register_frame_info_table} {__register_frame_info_table_bases} {__register_frame_table} {__rename}
		{__rmdir} {__rshift_D2A} {__rv_alloc_D2A} {__s2b_D2A} {__sandbox_me} {__sandbox_mm}
		{__sandbox_ms} {__sandbox_msp} {__sclose} {__select} {__select_nocancel} {__sem_open}
		{__sem_wait} {__sem_wait_nocancel} {__semctl} {__semsys} {__semwait_signal} {__semwait_signal_nocancel}
		{__sendmsg} {__sendmsg_nocancel} {__sendto} {__sendto_nocancel} {__set_ones_D2A} {__setattrlist}
		{__setlcid} {__setlogin} {__setonlyClocaleconv} {__setregid} {__setreuid} {__setrlimit}
		{__setsgroups} {__settid} {__settid_with_pid} {__settimeofday} {__setwgroups} {__sflags}
		{__sflush} {__sfp} {__sfvwrite} {__shared_region_check_np} {__shared_region_map_and_slide_np} {__shm_open}
		{__shmctl} {__shmsys} {__sigaction} {__sigaltstack} {__signbit} {__signbitd}
		{__signbitf} {__signbitl} {__sigreturn} {__sigsuspend} {__sigsuspend_nocancel} {__sigwait}
		{__sincos} {__sincos_stret} {__sincosf} {__sincosf_stret} {__sincospi} {__sincospi_stret}
		{__sincospif} {__sincospif_stret} {__sinit} {__sinpi} {__sinpif} {__slbexpand}
		{__smakebuf} {__snprintf_chk} {__socketpair} {__split_page} {__sprintf_chk} {__sread}
		{__srefill} {__srget} {__sseek} {__stack_chk_fail} {__stack_logging_early_finished} {__stack_logging_fork_child}
		{__stack_logging_fork_parent} {__stack_logging_fork_prepare} {__stack_snapshot} {__stat64_extended} {__stat_extended} {__stpcpy_chk}
		{__stpncpy_chk} {__strcat_chk} {__strcp_D2A} {__strcpy_chk} {__strlcat_chk} {__strlcpy_chk}
		{__strncat_chk} {__strncpy_chk} {__strtodg} {__strtodg$UNIX2003} {__strtopdd} {__strtopx}
		{__subvdi3} {__subvsi3} {__sum_D2A} {__svfscanf} {__swbuf} {__swhatbuf}
		{__swrite} {__swsetup} {__syscall} {__sysctl} {__tanpi} {__tanpif}
		{__telemetry} {__thread_selfid} {__tolower} {__tolower_l} {__toupper} {__toupper_l}
		{__trailz_D2A} {__ucmpdi2} {__udivdi3} {__udivmoddi4} {__ulp_D2A} {__umask_extended}
		{__umoddi3} {__ungetc} {__ungetwc} {__unlink} {__user_local_dirname} {__user_local_mkdir_p}
		{__vfork} {__vsnprintf_chk} {__vsprintf_chk} {__wait4} {__wait4_nocancel} {__waitid}
		{__waitid_nocancel} {__wcwidth} {__wcwidth_l} {__workq_kernreturn} {__workq_open} {__write}
		{__write_nocancel} {__writev} {__writev_nocancel} {__xdrrec_getrec} {__xdrrec_setnonblock} {_allocenvstate}
		{_authenticate} {_cleanup} {_closeutx} {_copyenv} {_cthread_fork_child} {_cthread_fork_parent}
		{_cthread_fork_prepare} {_deallocenvstate} {_ds_running} {_endutxent} {_exit} {_flockfile_debug_stub}
		{_fseeko} {_fsi_free_file_netgroup} {_fsi_get_line} {_fsi_tokenize} {_ftello} {_fwalk}
		{_gai_addr_sort} {_gai_serv_to_port} {_gai_simple} {_get_cpu_capabilities} {_getaddrinfo_interface_async_call} {_getenvp}
		{_getlong} {_getnameinfo_interface_async_call} {_getprivatesystemidentifier} {_getshort} {_getutxent} {_getutxid}
		{_getutxline} {_host_page_size} {_inet_aton_check} {_init_clock_port} {_init_cpu_capabilities} {_int_to_time}
		{_kernelrpc_mach_port_allocate} {_kernelrpc_mach_port_allocate_full} {_kernelrpc_mach_port_allocate_name} {_kernelrpc_mach_port_allocate_qos} {_kernelrpc_mach_port_allocate_trap} {_kernelrpc_mach_port_construct}
		{_kernelrpc_mach_port_construct_trap} {_kernelrpc_mach_port_deallocate} {_kernelrpc_mach_port_deallocate_trap} {_kernelrpc_mach_port_destroy} {_kernelrpc_mach_port_destroy_trap} {_kernelrpc_mach_port_destruct}
		{_kernelrpc_mach_port_destruct_trap} {_kernelrpc_mach_port_dnrequest_info} {_kernelrpc_mach_port_extract_member} {_kernelrpc_mach_port_extract_member_trap} {_kernelrpc_mach_port_extract_right} {_kernelrpc_mach_port_get_attributes}
		{_kernelrpc_mach_port_get_context} {_kernelrpc_mach_port_get_refs} {_kernelrpc_mach_port_get_set_status} {_kernelrpc_mach_port_get_srights} {_kernelrpc_mach_port_guard} {_kernelrpc_mach_port_guard_trap}
		{_kernelrpc_mach_port_insert_member} {_kernelrpc_mach_port_insert_member_trap} {_kernelrpc_mach_port_insert_right} {_kernelrpc_mach_port_insert_right_trap} {_kernelrpc_mach_port_kernel_object} {_kernelrpc_mach_port_kobject}
		{_kernelrpc_mach_port_mod_refs} {_kernelrpc_mach_port_mod_refs_trap} {_kernelrpc_mach_port_move_member} {_kernelrpc_mach_port_move_member_trap} {_kernelrpc_mach_port_names} {_kernelrpc_mach_port_peek}
		{_kernelrpc_mach_port_rename} {_kernelrpc_mach_port_request_notification} {_kernelrpc_mach_port_set_attributes} {_kernelrpc_mach_port_set_context} {_kernelrpc_mach_port_set_mscount} {_kernelrpc_mach_port_set_seqno}
		{_kernelrpc_mach_port_space_info} {_kernelrpc_mach_port_type} {_kernelrpc_mach_port_unguard} {_kernelrpc_mach_port_unguard_trap} {_kernelrpc_mach_vm_allocate} {_kernelrpc_mach_vm_allocate_trap}
		{_kernelrpc_mach_vm_deallocate} {_kernelrpc_mach_vm_deallocate_trap} {_kernelrpc_mach_vm_map} {_kernelrpc_mach_vm_map_trap} {_kernelrpc_mach_vm_protect} {_kernelrpc_mach_vm_protect_trap}
		{_kernelrpc_mach_vm_read} {_kernelrpc_mach_vm_remap} {_kernelrpc_task_set_port_space} {_kernelrpc_vm_map} {_kernelrpc_vm_read} {_kernelrpc_vm_remap}
		{_keymgr_get_and_lock_processwide_ptr} {_keymgr_get_and_lock_processwide_ptr_2} {_keymgr_get_lock_count_processwide_ptr} {_keymgr_get_lockmode_processwide_ptr} {_keymgr_set_and_unlock_processwide_ptr} {_keymgr_set_lockmode_processwide_ptr}
		{_keymgr_unlock_processwide_ptr} {_libc_fork_child} {_long_to_time} {_longjmp} {_mach_fork_child} {_mach_make_memory_entry}
		{_mach_snprintf} {_mach_vsnprintf} {_malloc_fork_child} {_malloc_fork_parent} {_malloc_fork_prepare} {_map_v4v6_address}
		{_map_v4v6_hostent} {_mkpath_np} {_mktemp} {_nc_list_append} {_nc_list_chop} {_nc_list_concat}
		{_nc_list_count} {_nc_list_data} {_nc_list_extract} {_nc_list_find} {_nc_list_find_release} {_nc_list_head}
		{_nc_list_new} {_nc_list_next} {_nc_list_prepend} {_nc_list_prev} {_nc_list_release} {_nc_list_release_list}
		{_nc_list_retain} {_nc_list_retain_list} {_nc_list_reverse} {_nc_list_set_data} {_nc_list_set_next} {_nc_list_set_prev}
		{_nc_list_tail} {_nc_table_delete} {_nc_table_delete_64} {_nc_table_delete_n} {_nc_table_find} {_nc_table_find_64}
		{_nc_table_find_get_key} {_nc_table_find_n} {_nc_table_free} {_nc_table_insert} {_nc_table_insert_64} {_nc_table_insert_n}
		{_nc_table_insert_no_copy} {_nc_table_insert_pass} {_nc_table_new} {_nc_table_traverse} {_nc_table_traverse_end} {_nc_table_traverse_start}
		{_notify_fork_child} {_notify_lib_cancel} {_notify_lib_cancel_port} {_notify_lib_cancel_proc} {_notify_lib_check} {_notify_lib_check_addr}
		{_notify_lib_check_controlled_access} {_notify_lib_get_access} {_notify_lib_get_owner} {_notify_lib_get_state} {_notify_lib_notify_state_free} {_notify_lib_notify_state_new}
		{_notify_lib_peek} {_notify_lib_port_proc_find} {_notify_lib_port_proc_new} {_notify_lib_port_proc_release} {_notify_lib_post} {_notify_lib_post_client}
		{_notify_lib_post_nid} {_notify_lib_register_file_descriptor} {_notify_lib_register_mach_port} {_notify_lib_register_plain} {_notify_lib_register_signal} {_notify_lib_release_name}
		{_notify_lib_resume} {_notify_lib_resume_port} {_notify_lib_resume_proc} {_notify_lib_set_access} {_notify_lib_set_owner} {_notify_lib_set_state}
		{_notify_lib_suspend} {_notify_lib_suspend_port} {_notify_lib_suspend_proc} {_notify_server_cancel} {_notify_server_cancel_2} {_notify_server_check}
		{_notify_server_get_access} {_notify_server_get_owner} {_notify_server_get_state} {_notify_server_get_state_2} {_notify_server_get_state_3} {_notify_server_monitor_file}
		{_notify_server_monitor_file_2} {_notify_server_post} {_notify_server_post_2} {_notify_server_post_3} {_notify_server_post_4} {_notify_server_regenerate}
		{_notify_server_register_check} {_notify_server_register_check_2} {_notify_server_register_file_descriptor} {_notify_server_register_file_descriptor_2} {_notify_server_register_mach_port} {_notify_server_register_mach_port_2}
		{_notify_server_register_plain} {_notify_server_register_plain_2} {_notify_server_register_signal} {_notify_server_register_signal_2} {_notify_server_release_name} {_notify_server_resume}
		{_notify_server_resume_pid} {_notify_server_set_access} {_notify_server_set_owner} {_notify_server_set_state} {_notify_server_set_state_2} {_notify_server_set_state_3}
		{_notify_server_simple_post} {_notify_server_suspend} {_notify_server_suspend_pid} {_old_endnetgrent} {_old_endrpcent} {_old_getnetgrent}
		{_old_getrpcbyname} {_old_getrpcbynumber} {_old_getrpcent} {_old_innetgr} {_old_setnetgrent} {_old_setrpcent}
		{_openutx} {_os_alloc_once} {_os_assert_log} {_os_assert_log_ctx} {_os_assumes_log} {_os_assumes_log_ctx}
		{_os_avoid_tail_call} {_os_once} {_os_semaphore_create} {_os_semaphore_dispose} {_os_semaphore_signal} {_os_semaphore_wait}
		{_os_trace} {_os_trace_error_str} {_osx_assert_log} {_osx_assert_log_ctx} {_osx_assumes_log} {_osx_assumes_log_ctx}
		{_osx_avoid_tail_call} {_platform_bzero} {_platform_memccpy} {_platform_memchr} {_platform_memcmp} {_platform_memmove}
		{_platform_memset} {_platform_memset_pattern16} {_platform_memset_pattern4} {_platform_memset_pattern8} {_platform_strchr} {_platform_strcmp}
		{_platform_strncmp} {_pthread_exit_if_canceled} {_pthread_fork_child} {_pthread_fork_child_postinit} {_pthread_fork_parent} {_pthread_fork_prepare}
		{_pthread_is_threaded} {_pthread_mutex_init} {_pthread_self} {_pthread_set_pfz} {_pthread_set_self} {_pthread_start}
		{_pthread_testcancel} {_pthread_wqthread} {_putenvp} {_pututxline} {_readdir_unlocked} {_readdir_unlocked$INODE64}
		{_reclaim_telldir} {_register_gethostuuid_callback} {_rpc_dtablesize} {_seekdir} {_seekdir$INODE64$UNIX2003} {_seekdir$UNIX2003}
		{_setenvp} {_seterr_reply} {_setjmp} {_setutxent} {_si_disable_opendirectory} {_sigaction_nobind}
		{_signal_nobind} {_sigtramp} {_sigunaltstack} {_sigvec_nobind} {_simple_asl_log} {_simple_asl_log_prog}
		{_simple_asl_msg_new} {_simple_asl_msg_set} {_simple_asl_send} {_simple_dprintf} {_simple_esappend} {_simple_esprintf}
		{_simple_getenv} {_simple_put} {_simple_putline} {_simple_salloc} {_simple_sappend} {_simple_sfree}
		{_simple_sprintf} {_simple_sresize} {_simple_string} {_simple_vdprintf} {_simple_vesprintf} {_simple_vsprintf}
		{_spin_lock} {_spin_lock_try} {_spin_unlock} {_sread} {_sseek} {_svcauth_null}
		{_svcauth_short} {_svcauth_unix} {_swrite} {_sysenter_trap} {_time32_to_time} {_time64_to_time}
		{_time_to_int} {_time_to_long} {_time_to_time32} {_time_to_time64} {_tztab} {_unsetenvp}
		{_utmpxname} {_yp_dobind} {_yp_unbind} {a64l} {abort} {abs}
		{accept} {accept$NOCANCEL$UNIX2003} {accept$UNIX2003} {access} {accessx_np} {acct}
		{acl_add_flag_np} {acl_add_perm} {acl_calc_mask} {acl_clear_flags_np} {acl_clear_perms} {acl_copy_entry}
		{acl_copy_ext} {acl_copy_ext_native} {acl_copy_int} {acl_copy_int_native} {acl_create_entry} {acl_create_entry_np}
		{acl_delete_def_file} {acl_delete_entry} {acl_delete_fd_np} {acl_delete_file_np} {acl_delete_flag_np} {acl_delete_link_np}
		{acl_delete_perm} {acl_dup} {acl_free} {acl_from_text} {acl_get_entry} {acl_get_fd}
		{acl_get_fd_np} {acl_get_file} {acl_get_flag_np} {acl_get_flagset_np} {acl_get_link_np} {acl_get_perm_np}
		{acl_get_permset} {acl_get_permset_mask_np} {acl_get_qualifier} {acl_get_tag_type} {acl_init} {acl_maximal_permset_mask_np}
		{acl_set_fd} {acl_set_fd_np} {acl_set_file} {acl_set_flagset_np} {acl_set_link_np} {acl_set_permset}
		{acl_set_permset_mask_np} {acl_set_qualifier} {acl_set_tag_type} {acl_size} {acl_to_text} {acl_valid}
		{acl_valid_fd_np} {acl_valid_file_np} {acl_valid_link} {acos} {acos$fenv_access_off} {acosf}
		{acosf$fenv_access_off} {acosh} {acosh$fenv_access_off} {acoshf} {acoshf$fenv_access_off} {acoshl}
		{acoshl$fenv_access_off} {acosl} {acosl$fenv_access_off} {act_get_state} {act_set_state} {addr2ascii}
		{adjtime} {aio_cancel} {aio_error} {aio_fsync} {aio_read} {aio_return}
		{aio_suspend} {aio_suspend$NOCANCEL$UNIX2003} {aio_suspend$UNIX2003} {aio_write} {alarm} {alias_endent}
		{alias_getbyname} {alias_getbyname_async_call} {alias_getbyname_async_handle_reply} {alias_getent} {alias_setent} {alphasort}
		{alphasort$INODE64} {arc4random} {arc4random_addrandom} {arc4random_buf} {arc4random_stir} {arc4random_uniform}
		{ascii2addr} {asctime} {asctime_r} {asin} {asin$fenv_access_off} {asinf}
		{asinf$fenv_access_off} {asinh} {asinh$fenv_access_off} {asinhf} {asinhf$fenv_access_off} {asinhl}
		{asinhl$fenv_access_off} {asinl} {asinl$fenv_access_off} {asprintf} {asprintf_l} {asxprintf}
		{asxprintf_exec} {atan} {atan$fenv_access_off} {atan2} {atan2$fenv_access_off} {atan2f}
		{atan2f$fenv_access_off} {atan2l} {atan2l$fenv_access_off} {atanf} {atanf$fenv_access_off} {atanh}
		{atanh$fenv_access_off} {atanhf} {atanhf$fenv_access_off} {atanhl} {atanhl$fenv_access_off} {atanl}
		{atanl$fenv_access_off} {atexit} {atexit_b} {atof} {atof_l} {atoi}
		{atoi_l} {atol} {atol_l} {atoll} {atoll_l} {audit}
		{audit_session_join} {audit_session_port} {audit_session_self} {auditctl} {auditon} {authnone_create}
		{authunix_create} {authunix_create_default} {backtrace} {backtrace_symbols} {backtrace_symbols_fd} {basename}
		{bcopy} {bind} {bind$UNIX2003} {bindresvport} {bindresvport_sa} {bitarray_create}
		{bitarray_first_set} {bitarray_get} {bitarray_set} {bitarray_size} {bitarray_zap} {bitarray_zap_first_set}
		{bitarray_zap_first_set_multiple} {bootp_getbyether} {bootp_getbyip} {bootparams_endent} {bootparams_getbyname} {bootparams_getent}
		{bootparams_setent} {brk} {bsd_signal} {bsearch} {bsearch_b} {btowc}
		{btowc_l} {cabs} {cabs$fenv_access_off} {cabsf} {cabsf$fenv_access_off} {cabsl}
		{cabsl$fenv_access_off} {cacos} {cacos$fenv_access_off} {cacosf} {cacosf$fenv_access_off} {cacosh}
		{cacosh$fenv_access_off} {cacoshf} {cacoshf$fenv_access_off} {cacoshl} {cacoshl$fenv_access_off} {cacosl}
		{cacosl$fenv_access_off} {calloc} {callrpc} {carg} {carg$fenv_access_off} {cargf}
		{cargf$fenv_access_off} {cargl} {cargl$fenv_access_off} {casin} {casin$fenv_access_off} {casinf}
		{casinf$fenv_access_off} {casinh} {casinh$fenv_access_off} {casinhf} {casinhf$fenv_access_off} {casinhl}
		{casinhl$fenv_access_off} {casinl} {casinl$fenv_access_off} {catan} {catan$fenv_access_off} {catanf}
		{catanf$fenv_access_off} {catanh} {catanh$fenv_access_off} {catanhf} {catanhf$fenv_access_off} {catanhl}
		{catanhl$fenv_access_off} {catanl} {catanl$fenv_access_off} {catclose} {catgets} {catopen}
		{cbrt} {cbrt$fenv_access_off} {cbrtf} {cbrtf$fenv_access_off} {cbrtl} {cbrtl$fenv_access_off}
		{ccos} {ccos$fenv_access_off} {ccosf} {ccosf$fenv_access_off} {ccosh} {ccosh$fenv_access_off}
		{ccoshf} {ccoshf$fenv_access_off} {ccoshl} {ccoshl$fenv_access_off} {ccosl} {ccosl$fenv_access_off}
		{ceil} {ceil$fenv_access_off} {ceilf} {ceilf$fenv_access_off} {ceill} {ceill$fenv_access_off}
		{cerror} {cerror_nocancel} {cexp} {cexp$fenv_access_off} {cexpf} {cexpf$fenv_access_off}
		{cexpl} {cexpl$fenv_access_off} {cfgetispeed} {cfgetospeed} {cfmakeraw} {cfsetispeed}
		{cfsetospeed} {cfsetspeed} {cgetcap} {cgetclose} {cgetent} {cgetfirst}
		{cgetmatch} {cgetnext} {cgetnum} {cgetset} {cgetstr} {cgetustr}
		{change_fdguard_np} {chdir} {chflags} {chmod} {chmod$UNIX2003} {chmodx_np}
		{chown} {chroot} {cimag} {cimag$fenv_access_off} {cimagf} {cimagf$fenv_access_off}
		{cimagl} {cimagl$fenv_access_off} {clearerr} {clearerr_unlocked} {clnt_broadcast} {clnt_create}
		{clnt_pcreateerror} {clnt_perrno} {clnt_perror} {clnt_spcreateerror} {clnt_sperrno} {clnt_sperror}
		{clntraw_create} {clnttcp_create} {clnttcp_create_timeout} {clntudp_bufcreate} {clntudp_bufcreate_timeout} {clntudp_create}
		{clock} {clock$UNIX2003} {clock_alarm} {clock_alarm_reply} {clock_get_attributes} {clock_get_time}
		{clock_set_attributes} {clock_set_time} {clock_sleep} {clock_sleep_trap} {clog} {clog$fenv_access_off}
		{clogf} {clogf$fenv_access_off} {clogl} {clogl$fenv_access_off} {close} {close$NOCANCEL$UNIX2003}
		{close$UNIX2003} {closedir} {closedir$UNIX2003} {compat_mode} {configuration_profile_copy_property_list} {configuration_profile_create_notification_key}
		{confstr} {confstr$UNIX2003} {conj} {conj$fenv_access_off} {conjf} {conjf$fenv_access_off}
		{conjl} {conjl$fenv_access_off} {connect} {connect$NOCANCEL$UNIX2003} {connect$UNIX2003} {connectx}
		{copy_printf_domain} {copysign} {copysign$fenv_access_off} {copysignf} {copysignf$fenv_access_off} {copysignl}
		{copysignl$fenv_access_off} {cos} {cos$fenv_access_off} {cosf} {cosf$fenv_access_off} {cosh}
		{cosh$fenv_access_off} {coshf} {coshf$fenv_access_off} {coshl} {coshl$fenv_access_off} {cosl}
		{cosl$fenv_access_off} {cpow} {cpow$fenv_access_off} {cpowf} {cpowf$fenv_access_off} {cpowl}
		{cpowl$fenv_access_off} {cproj} {cproj$fenv_access_off} {cprojf} {cprojf$fenv_access_off} {cprojl}
		{cprojl$fenv_access_off} {creal} {creal$fenv_access_off} {crealf} {crealf$fenv_access_off} {creall}
		{creall$fenv_access_off} {creat} {creat$NOCANCEL$UNIX2003} {creat$UNIX2003} {create_scalable_zone} {crypt}
		{csin} {csin$fenv_access_off} {csinf} {csinf$fenv_access_off} {csinh} {csinh$fenv_access_off}
		{csinhf} {csinhf$fenv_access_off} {csinhl} {csinhl$fenv_access_off} {csinl} {csinl$fenv_access_off}
		{csops} {csops_audittoken} {csqrt} {csqrt$fenv_access_off} {csqrtf} {csqrtf$fenv_access_off}
		{csqrtl} {csqrtl$fenv_access_off} {ctan} {ctan$fenv_access_off} {ctanf} {ctanf$fenv_access_off}
		{ctanh} {ctanh$fenv_access_off} {ctanhf} {ctanhf$fenv_access_off} {ctanhl} {ctanhl$fenv_access_off}
		{ctanl} {ctanl$fenv_access_off} {ctermid} {ctermid_r} {cthread_set_errno_self} {cthread_yield}
		{ctime} {ctime_r} {daemon} {daemon$1050} {dbm_clearerr} {dbm_close}
		{dbm_delete} {dbm_dirfno} {dbm_error} {dbm_fetch} {dbm_firstkey} {dbm_nextkey}
		{dbm_open} {dbm_store} {dbopen} {devname} {devname_r} {difftime}
		{digittoint} {digittoint_l} {dirfd} {dirname} {disconnectx} {div}
		{dn_expand} {dprintf} {dprintf_l} {drand48} {drem} {dup}
		{dup2} {duplocale} {dxprintf} {dxprintf_exec} {ecvt} {encrypt}
		{encrypt$UNIX2003} {endfsent} {endgrent} {endhostent} {endnetent} {endnetgrent}
		{endprotoent} {endpwent} {endrpcent} {endservent} {endttyent} {endusershell}
		{endutxent} {endutxent_wtmp} {erand48} {erf} {erf$fenv_access_off} {erfc}
		{erfc$fenv_access_off} {erfcf} {erfcf$fenv_access_off} {erfcl} {erfcl$fenv_access_off} {erff}
		{erff$fenv_access_off} {erfl} {erfl$fenv_access_off} {err} {err_set_exit} {err_set_exit_b}
		{err_set_file} {errc} {errx} {etap_trace_thread} {ether_aton} {ether_hostton}
		{ether_line} {ether_ntoa} {ether_ntohost} {exc_server} {exc_server_routine} {exception_raise}
		{exception_raise_state} {exception_raise_state_identity} {exchangedata} {execl} {execle} {execlp}
		{execv} {execvP} {execve} {execvp} {exit} {exp}
		{exp$fenv_access_off} {exp2} {exp2$fenv_access_off} {exp2f} {exp2f$fenv_access_off} {exp2l}
		{exp2l$fenv_access_off} {expf} {expf$fenv_access_off} {expl} {expl$fenv_access_off} {expm1}
		{expm1$fenv_access_off} {expm1f} {expm1f$fenv_access_off} {expm1l} {expm1l$fenv_access_off} {f_prealloc}
		{fabs} {fabs$fenv_access_off} {fabsf} {fabsf$fenv_access_off} {fabsl} {fabsl$fenv_access_off}
		{fchdir} {fchflags} {fchmod} {fchmod$UNIX2003} {fchmodx_np} {fchown}
		{fclose} {fcntl} {fcntl$NOCANCEL$UNIX2003} {fcntl$UNIX2003} {fcvt} {fdatasync}
		{fdim} {fdim$fenv_access_off} {fdimf} {fdimf$fenv_access_off} {fdiml} {fdiml$fenv_access_off}
		{fdopen} {fdopen$DARWIN_EXTSN} {fdopen$UNIX2003} {feclearexcept} {fegetenv} {fegetexcept}
		{fegetexceptflag} {fegetround} {feholdexcept} {feof} {feof_unlocked} {feraiseexcept}
		{ferror} {ferror_unlocked} {fesetenv} {fesetexcept} {fesetexceptflag} {fesetround}
		{fetestexcept} {feupdateenv} {fflagstostr} {fflush} {ffs} {ffsctl}
		{ffsl} {ffsll} {fgetattrlist} {fgetc} {fgetln} {fgetpos}
		{fgetrune} {fgets} {fgetwc} {fgetwc_l} {fgetwln} {fgetwln_l}
		{fgetws} {fgetws_l} {fgetxattr} {fhopen} {fileno} {fileno_unlocked}
		{fileport_makefd} {fileport_makeport} {filesec_dup} {filesec_free} {filesec_get_property} {filesec_init}
		{filesec_query_property} {filesec_set_property} {filesec_unset_property} {finite} {flistxattr} {flock}
		{flockfile} {floor} {floor$fenv_access_off} {floorf} {floorf$fenv_access_off} {floorl}
		{floorl$fenv_access_off} {fls} {flsl} {flsll} {fma} {fma$fenv_access_off}
		{fmaf} {fmaf$fenv_access_off} {fmal} {fmal$fenv_access_off} {fmax} {fmax$fenv_access_off}
		{fmaxf} {fmaxf$fenv_access_off} {fmaxl} {fmaxl$fenv_access_off} {fmin} {fmin$fenv_access_off}
		{fminf} {fminf$fenv_access_off} {fminl} {fminl$fenv_access_off} {fmod} {fmod$fenv_access_off}
		{fmodf} {fmodf$fenv_access_off} {fmodl} {fmodl$fenv_access_off} {fmtcheck} {fmtmsg}
		{fnmatch} {fnmatch$UNIX2003} {fopen} {fopen$DARWIN_EXTSN} {fopen$UNIX2003} {fork}
		{forkpty} {fparseln} {fpathconf} {fprintf} {fprintf_l} {fpurge}
		{fputc} {fputrune} {fputs} {fputs$UNIX2003} {fputwc} {fputwc_l}
		{fputws} {fputws_l} {fread} {free} {free_printf_comp} {free_printf_domain}
		{freeaddrinfo} {freehostent} {freeifaddrs} {freeifmaddrs} {freelocale} {fremovexattr}
		{freopen} {freopen$UNIX2003} {frexp} {frexp$fenv_access_off} {frexpf} {frexpf$fenv_access_off}
		{frexpl} {frexpl$fenv_access_off} {fscanf} {fscanf_l} {fsctl} {fseek}
		{fseeko} {fsetattrlist} {fsetpos} {fsetxattr} {fstat} {fstat$INODE64}
		{fstat64} {fstatfs} {fstatfs$INODE64} {fstatfs64} {fstatvfs} {fstatx64_np}
		{fstatx_np} {fstatx_np$INODE64} {fsync} {fsync$NOCANCEL$UNIX2003} {fsync$UNIX2003} {fsync_volume_np}
		{ftell} {ftello} {ftime} {ftok} {ftruncate} {ftrylockfile}
		{fts_children} {fts_children$INODE64} {fts_close} {fts_close$INODE64} {fts_open} {fts_open$INODE64}
		{fts_open_b} {fts_open_b$INODE64} {fts_read} {fts_read$INODE64} {fts_set} {fts_set$INODE64}
		{ftw} {ftw$INODE64$UNIX2003} {ftw$UNIX2003} {fungetrune} {funlockfile} {funopen}
		{futimes} {fwide} {fwprintf} {fwprintf_l} {fwrite} {fwrite$UNIX2003}
		{fwscanf} {fwscanf_l} {fxprintf} {fxprintf_exec} {gai_strerror} {gamma}
		{gamma$fenv_access_off} {gcvt} {get_dp_control_port} {get_myaddress} {get_rdata} {get_string}
		{get_uint16} {get_uint32} {getaddrinfo} {getaddrinfo_async_call} {getaddrinfo_async_cancel} {getaddrinfo_async_handle_reply}
		{getaddrinfo_async_receive} {getaddrinfo_async_send} {getaddrinfo_async_start} {getattrlist} {getattrlist$UNIX2003} {getaudit}
		{getaudit_addr} {getauid} {getbsize} {getc} {getc_unlocked} {getchar}
		{getchar_unlocked} {getcontext} {getcwd} {getdate} {getdelim} {getdirentries}
		{getdirentriesattr} {getdiskbyname} {getdomainname} {getdtablesize} {getegid} {getenv}
		{geteuid} {getfh} {getfsbyname} {getfsent} {getfsfile} {getfsfile_async_call}
		{getfsfile_async_handle_reply} {getfsspec} {getfsspec_async_call} {getfsspec_async_handle_reply} {getfsstat} {getfsstat$INODE64}
		{getfsstat64} {getgid} {getgrent} {getgrgid} {getgrgid_async_call} {getgrgid_r}
		{getgrnam} {getgrnam_async_call} {getgrnam_async_handle_reply} {getgrnam_r} {getgroupcount} {getgrouplist}
		{getgrouplist_2} {getgroups} {getgroups$DARWIN_EXTSN} {getgruid_async_handle_reply} {getgruuid} {getgruuid_r}
		{gethostbyaddr} {gethostbyaddr_async_call} {gethostbyaddr_async_cancel} {gethostbyaddr_async_handleReply} {gethostbyaddr_async_start} {gethostbyname}
		{gethostbyname2} {gethostbyname2_async_call} {gethostbyname2_async_cancel} {gethostbyname2_async_handle_reply} {gethostbyname_async_call} {gethostbyname_async_cancel}
		{gethostbyname_async_handleReply} {gethostbyname_async_start} {gethostbynameerrno} {gethostent} {gethostid} {gethostname}
		{gethostuuid} {getifaddrs} {getifmaddrs} {getiopolicy_np} {getipnodebyaddr} {getipnodebyname}
		{getipv4sourcefilter} {getitimer} {getlastlogx} {getlastlogxbyname} {getline} {getloadavg}
		{getlogin} {getlogin_r} {getmntinfo} {getmntinfo$INODE64} {getmntinfo64} {getmode}
		{getnameinfo} {getnameinfo_async_call} {getnameinfo_async_cancel} {getnameinfo_async_handle_reply} {getnameinfo_async_send} {getnameinfo_async_start}
		{getnetbyaddr} {getnetbyaddr_async_call} {getnetbyaddr_async_handle_reply} {getnetbyname} {getnetbyname_async_call} {getnetbyname_async_handle_reply}
		{getnetent} {getnetgrent} {getopt} {getopt$UNIX2003} {getopt_long} {getopt_long_only}
		{getpagesize} {getpass} {getpeereid} {getpeername} {getpeername$UNIX2003} {getpgid}
		{getpgrp} {getpid} {getppid} {getpriority} {getprogname} {getprotobyname}
		{getprotobyname_async_call} {getprotobyname_async_handle_reply} {getprotobynumber} {getprotobynumber_async_call} {getprotobynumber_async_handle_reply} {getprotoent}
		{getpwent} {getpwnam} {getpwnam_async_call} {getpwnam_async_handle_reply} {getpwnam_r} {getpwuid}
		{getpwuid_async_call} {getpwuid_async_handle_reply} {getpwuid_r} {getpwuuid} {getpwuuid_r} {getrlimit}
		{getrlimit$UNIX2003} {getrpcbyname} {getrpcbyname_async_call} {getrpcbyname_async_handle_reply} {getrpcbynumber} {getrpcbynumber_async_call}
		{getrpcbynumber_async_handle_reply} {getrpcent} {getrpcport} {getrusage} {gets} {getservbyname}
		{getservbyname_async_call} {getservbyname_async_handle_reply} {getservbyport} {getservbyport_async_call} {getservbyport_async_handle_reply} {getservent}
		{getsgroups_np} {getsid} {getsockname} {getsockname$UNIX2003} {getsockopt} {getsourcefilter}
		{getsubopt} {gettimeofday} {getttyent} {getttynam} {getuid} {getusershell}
		{getutmp} {getutmpx} {getutxent} {getutxent_wtmp} {getutxid} {getutxline}
		{getvfsbyname} {getw} {getwc} {getwc_l} {getwchar} {getwchar_l}
		{getwd} {getwgroups_np} {getxattr} {glob} {glob$INODE64} {glob_b}
		{glob_b$INODE64} {globfree} {gmtime} {gmtime_r} {grantpt} {group_from_gid}
		{guarded_close_np} {guarded_kqueue_np} {guarded_open_np} {hash_create} {hash_destroy} {hash_purge}
		{hash_search} {hash_stats} {hash_traverse} {hcreate} {hdestroy} {heapsort}
		{heapsort_b} {herror} {host_default_memory_manager} {host_get_UNDServer} {host_get_boot_info} {host_get_clock_control}
		{host_get_clock_service} {host_get_exception_ports} {host_get_io_master} {host_get_special_port} {host_info} {host_kernel_version}
		{host_lockgroup_info} {host_page_size} {host_priv_statistics} {host_processor_info} {host_processor_set_priv} {host_processor_sets}
		{host_processors} {host_reboot} {host_request_notification} {host_security_create_task_token} {host_security_set_task_token} {host_self}
		{host_self_trap} {host_set_UNDServer} {host_set_exception_ports} {host_set_special_port} {host_statistics} {host_statistics64}
		{host_swap_exception_ports} {host_virtual_physical_table_info} {host_zone_info} {hsearch} {hstrerror} {htonl}
		{htons} {hypot} {hypot$fenv_access_off} {hypotf} {hypotf$fenv_access_off} {hypotl}
		{hypotl$fenv_access_off} {i386_get_ldt} {i386_set_ldt} {if_freenameindex} {if_indextoname} {if_nameindex}
		{if_nametoindex} {ilogb} {ilogb$fenv_access_off} {ilogbf} {ilogbf$fenv_access_off} {ilogbl}
		{ilogbl$fenv_access_off} {imaxabs} {imaxdiv} {index} {inet6_opt_append} {inet6_opt_find}
		{inet6_opt_finish} {inet6_opt_get_val} {inet6_opt_init} {inet6_opt_next} {inet6_opt_set_val} {inet6_option_alloc}
		{inet6_option_append} {inet6_option_find} {inet6_option_init} {inet6_option_next} {inet6_option_space} {inet6_rth_add}
		{inet6_rth_getaddr} {inet6_rth_init} {inet6_rth_reverse} {inet6_rth_segments} {inet6_rth_space} {inet6_rthdr_add}
		{inet6_rthdr_getaddr} {inet6_rthdr_getflags} {inet6_rthdr_init} {inet6_rthdr_lasthop} {inet6_rthdr_segments} {inet6_rthdr_space}
		{inet_addr} {inet_aton} {inet_lnaof} {inet_makeaddr} {inet_net_ntop} {inet_net_pton}
		{inet_neta} {inet_netof} {inet_network} {inet_nsap_addr} {inet_nsap_ntoa} {inet_ntoa}
		{inet_ntop} {inet_ntop4} {inet_ntop6} {inet_pton} {initgroups} {initstate}
		{innetgr} {insque} {internal_DNSServiceBrowserReply_rpc} {internal_DNSServiceDomainEnumerationReply_rpc} {internal_DNSServiceRegistrationReply_rpc} {internal_DNSServiceResolverReply_rpc}
		{ioctl} {iruserok} {iruserok_sa} {isalnum} {isalnum_l} {isalpha}
		{isalpha_l} {isascii} {isatty} {isblank} {isblank_l} {iscntrl}
		{iscntrl_l} {isdigit} {isdigit_l} {isgraph} {isgraph_l} {ishexnumber}
		{ishexnumber_l} {isideogram} {isideogram_l} {isinf} {islower} {islower_l}
		{isnan} {isnumber} {isnumber_l} {isphonogram} {isphonogram_l} {isprint}
		{isprint_l} {ispunct} {ispunct_l} {isrune} {isrune_l} {issetugid}
		{isspace} {isspace_l} {isspecial} {isspecial_l} {isupper} {isupper_l}
		{iswalnum} {iswalnum_l} {iswalpha} {iswalpha_l} {iswascii} {iswblank}
		{iswblank_l} {iswcntrl} {iswcntrl_l} {iswctype} {iswctype_l} {iswdigit}
		{iswdigit_l} {iswgraph} {iswgraph_l} {iswhexnumber} {iswhexnumber_l} {iswideogram}
		{iswideogram_l} {iswlower} {iswlower_l} {iswnumber} {iswnumber_l} {iswphonogram}
		{iswphonogram_l} {iswprint} {iswprint_l} {iswpunct} {iswpunct_l} {iswrune}
		{iswrune_l} {iswspace} {iswspace_l} {iswspecial} {iswspecial_l} {iswupper}
		{iswupper_l} {iswxdigit} {iswxdigit_l} {isxdigit} {isxdigit_l} {j0}
		{j1} {jn} {jrand48} {kas_info} {kevent} {kevent64}
		{kext_request} {kill} {kill$UNIX2003} {killpg} {killpg$UNIX2003} {kmod_control}
		{kmod_create} {kmod_destroy} {kmod_get_info} {kqueue} {kvarray_free} {kvbuf_add_dict}
		{kvbuf_add_key} {kvbuf_add_val} {kvbuf_add_val_len} {kvbuf_append_kvbuf} {kvbuf_decode} {kvbuf_free}
		{kvbuf_get_len} {kvbuf_init} {kvbuf_init_zone} {kvbuf_make_nonpurgeable} {kvbuf_make_purgeable} {kvbuf_new}
		{kvbuf_new_zone} {kvbuf_next_dict} {kvbuf_next_key} {kvbuf_next_val} {kvbuf_next_val_len} {kvbuf_query}
		{kvbuf_query_key_int} {kvbuf_query_key_uint} {kvbuf_query_key_val} {kvbuf_reset} {kvm_close} {kvm_getargv}
		{kvm_getenvv} {kvm_geterr} {kvm_getfiles} {kvm_getloadavg} {kvm_getprocs} {kvm_nlist}
		{kvm_open} {kvm_openfiles} {kvm_read} {kvm_uread} {kvm_write} {l64a}
		{labs} {lchflags} {lchmod} {lchown} {lchown$UNIX2003} {lcong48}
		{ldexp} {ldexp$fenv_access_off} {ldexpf} {ldexpf$fenv_access_off} {ldexpl} {ldexpl$fenv_access_off}
		{ldiv} {ledger} {lfind} {lgamma} {lgamma$fenv_access_off} {lgamma_r}
		{lgamma_r$fenv_access_off} {lgammaf} {lgammaf$fenv_access_off} {lgammaf_r} {lgammaf_r$fenv_access_off} {lgammal}
		{lgammal$fenv_access_off} {lgammal_r} {lgammal_r$fenv_access_off} {link} {link_addr} {link_ntoa}
		{lio_listio} {listen} {listen$UNIX2003} {listxattr} {llabs} {lldiv}
		{llrint} {llrint$fenv_access_off} {llrintf} {llrintf$fenv_access_off} {llrintl} {llrintl$fenv_access_off}
		{llround} {llround$fenv_access_off} {llroundf} {llroundf$fenv_access_off} {llroundl} {llroundl$fenv_access_off}
		{localeconv} {localeconv_l} {localtime} {localtime_r} {lock_acquire} {lock_handoff}
		{lock_handoff_accept} {lock_make_stable} {lock_release} {lock_set_create} {lock_set_destroy} {lock_try}
		{lockf} {lockf$NOCANCEL$UNIX2003} {lockf$UNIX2003} {log} {log$fenv_access_off} {log10}
		{log10$fenv_access_off} {log10f} {log10f$fenv_access_off} {log10l} {log10l$fenv_access_off} {log1p}
		{log1p$fenv_access_off} {log1pf} {log1pf$fenv_access_off} {log1pl} {log1pl$fenv_access_off} {log2}
		{log2$fenv_access_off} {log2f} {log2f$fenv_access_off} {log2l} {log2l$fenv_access_off} {logb}
		{logb$fenv_access_off} {logbf} {logbf$fenv_access_off} {logbl} {logbl$fenv_access_off} {logf}
		{logf$fenv_access_off} {login} {login_tty} {logl} {logl$fenv_access_off} {logout}
		{logwtmp} {longjmp} {longjmperror} {lrand48} {lrint} {lrint$fenv_access_off}
		{lrintf} {lrintf$fenv_access_off} {lrintl} {lrintl$fenv_access_off} {lround} {lround$fenv_access_off}
		{lroundf} {lroundf$fenv_access_off} {lroundl} {lroundl$fenv_access_off} {lsearch} {lseek}
		{lstat} {lstat$INODE64} {lstat64} {lstatx64_np} {lstatx_np} {lstatx_np$INODE64}
		{lutimes} {mach_absolute_time} {mach_error} {mach_error_string} {mach_error_type} {mach_host_self}
		{mach_init} {mach_make_memory_entry} {mach_make_memory_entry_64} {mach_memory_object_memory_entry} {mach_memory_object_memory_entry_64} {mach_msg}
		{mach_msg_destroy} {mach_msg_overwrite} {mach_msg_overwrite_trap} {mach_msg_receive} {mach_msg_send} {mach_msg_server}
		{mach_msg_server_importance} {mach_msg_server_once} {mach_msg_trap} {mach_notify_dead_name} {mach_notify_no_senders} {mach_notify_port_deleted}
		{mach_notify_port_destroyed} {mach_notify_send_once} {mach_port_allocate} {mach_port_allocate_full} {mach_port_allocate_name} {mach_port_allocate_qos}
		{mach_port_construct} {mach_port_deallocate} {mach_port_destroy} {mach_port_destruct} {mach_port_dnrequest_info} {mach_port_extract_member}
		{mach_port_extract_right} {mach_port_get_attributes} {mach_port_get_context} {mach_port_get_refs} {mach_port_get_set_status} {mach_port_get_srights}
		{mach_port_guard} {mach_port_insert_member} {mach_port_insert_right} {mach_port_kernel_object} {mach_port_kobject} {mach_port_mod_refs}
		{mach_port_move_member} {mach_port_names} {mach_port_peek} {mach_port_rename} {mach_port_request_notification} {mach_port_set_attributes}
		{mach_port_set_context} {mach_port_set_mscount} {mach_port_set_seqno} {mach_port_space_info} {mach_port_type} {mach_port_unguard}
		{mach_ports_lookup} {mach_ports_register} {mach_reply_port} {mach_task_self} {mach_thread_self} {mach_timebase_info}
		{mach_vm_allocate} {mach_vm_behavior_set} {mach_vm_copy} {mach_vm_deallocate} {mach_vm_inherit} {mach_vm_machine_attribute}
		{mach_vm_map} {mach_vm_msync} {mach_vm_page_info} {mach_vm_page_query} {mach_vm_protect} {mach_vm_purgable_control}
		{mach_vm_read} {mach_vm_read_list} {mach_vm_read_overwrite} {mach_vm_region} {mach_vm_region_info} {mach_vm_region_info_64}
		{mach_vm_region_recurse} {mach_vm_remap} {mach_vm_wire} {mach_vm_write} {mach_wait_until} {mach_zone_force_gc}
		{mach_zone_info} {macx_backing_store_recovery} {macx_backing_store_suspend} {macx_swapoff} {macx_swapon} {macx_triggers}
		{madvise} {make_client_id} {makecontext} {malloc} {malloc_create_legacy_default_zone} {malloc_create_zone}
		{malloc_debug} {malloc_default_purgeable_zone} {malloc_default_zone} {malloc_destroy_zone} {malloc_engaged_nano} {malloc_error}
		{malloc_freezedry} {malloc_get_all_zones} {malloc_get_zone_name} {malloc_good_size} {malloc_jumpstart} {malloc_make_nonpurgeable}
		{malloc_make_purgeable} {malloc_printf} {malloc_set_zone_name} {malloc_singlethreaded} {malloc_size} {malloc_zone_batch_free}
		{malloc_zone_batch_malloc} {malloc_zone_calloc} {malloc_zone_check} {malloc_zone_disable_discharge_checking} {malloc_zone_discharge} {malloc_zone_enable_discharge_checking}
		{malloc_zone_enumerate_discharged_pointers} {malloc_zone_free} {malloc_zone_from_ptr} {malloc_zone_log} {malloc_zone_malloc} {malloc_zone_memalign}
		{malloc_zone_pressure_relief} {malloc_zone_print} {malloc_zone_print_ptr_info} {malloc_zone_realloc} {malloc_zone_register} {malloc_zone_statistics}
		{malloc_zone_unregister} {malloc_zone_valloc} {map_fd} {matherr} {mblen} {mblen_l}
		{mbmb} {mbr_check_membership} {mbr_check_membership_by_id} {mbr_check_membership_ext} {mbr_check_membership_refresh} {mbr_check_service_membership}
		{mbr_gid_to_uuid} {mbr_group_name_to_uuid} {mbr_identifier_to_uuid} {mbr_identifier_translate} {mbr_reset_cache} {mbr_set_identifier_ttl}
		{mbr_sid_to_string} {mbr_sid_to_uuid} {mbr_string_to_sid} {mbr_string_to_uuid} {mbr_uid_to_uuid} {mbr_user_name_to_uuid}
		{mbr_uuid_to_id} {mbr_uuid_to_sid} {mbr_uuid_to_sid_type} {mbr_uuid_to_string} {mbrlen} {mbrlen_l}
		{mbrrune} {mbrtowc} {mbrtowc_l} {mbrune} {mbsinit} {mbsinit_l}
		{mbsnrtowcs} {mbsnrtowcs_l} {mbsrtowcs} {mbsrtowcs_l} {mbstowcs} {mbstowcs_l}
		{mbtowc} {mbtowc_l} {memmem} {memorystatus_control} {memorystatus_get_level} {memset_s}
		{mergesort} {mergesort_b} {mig_allocate} {mig_dealloc_reply_port} {mig_deallocate} {mig_get_reply_port}
		{mig_put_reply_port} {mig_reply_setup} {mig_strncpy} {mincore} {minherit} {mk_timer_arm}
		{mk_timer_cancel} {mk_timer_create} {mk_timer_destroy} {mkdir} {mkdirx_np} {mkdtemp}
		{mkfifo} {mkfifox_np} {mknod} {mkpath_np} {mkstemp} {mkstemps}
		{mktemp} {mktime} {mktime$UNIX2003} {mlock} {mlockall} {mmap}
		{mmap$UNIX2003} {modf} {modf$fenv_access_off} {modff} {modff$fenv_access_off} {modfl}
		{modfl$fenv_access_off} {modwatch} {monaddition} {moncontrol} {moncount} {moninit}
		{monitor} {monoutput} {monreset} {monstartup} {mount} {mpool_close}
		{mpool_filter} {mpool_get} {mpool_new} {mpool_open} {mpool_put} {mpool_sync}
		{mprotect} {mprotect$UNIX2003} {mrand48} {msg_receive} {msg_rpc} {msg_send}
		{msgctl} {msgctl$UNIX2003} {msgget} {msgrcv} {msgrcv$NOCANCEL$UNIX2003} {msgrcv$UNIX2003}
		{msgsnd} {msgsnd$NOCANCEL$UNIX2003} {msgsnd$UNIX2003} {msgsys} {mstats} {msync}
		{msync$NOCANCEL$UNIX2003} {msync$UNIX2003} {munlock} {munlockall} {munmap} {munmap$UNIX2003}
		{nan} {nanf} {nanl} {nanosleep} {nanosleep$NOCANCEL$UNIX2003} {nanosleep$UNIX2003}
		{nearbyint} {nearbyint$fenv_access_off} {nearbyintf} {nearbyintf$fenv_access_off} {nearbyintl} {nearbyintl$fenv_access_off}
		{netname_check_in} {netname_check_out} {netname_look_up} {netname_version} {new_printf_comp} {new_printf_domain}
		{newlocale} {nextafter} {nextafter$fenv_access_off} {nextafterd} {nextafterf} {nextafterf$fenv_access_off}
		{nextafterl} {nextafterl$fenv_access_off} {nexttoward} {nexttoward$fenv_access_off} {nexttowardf} {nexttowardf$fenv_access_off}
		{nexttowardl} {nexttowardl$fenv_access_off} {nextwctype} {nextwctype_l} {nfsclnt} {nfssvc}
		{nftw} {nftw$INODE64$UNIX2003} {nftw$UNIX2003} {nice} {nice$UNIX2003} {nl_langinfo}
		{nl_langinfo_l} {nlist} {notify_cancel} {notify_check} {notify_check_addr} {notify_get_access}
		{notify_get_event} {notify_get_owner} {notify_get_state} {notify_monitor_file} {notify_peek} {notify_post}
		{notify_register_check} {notify_register_dispatch} {notify_register_file_descriptor} {notify_register_mach_port} {notify_register_plain} {notify_register_signal}
		{notify_release_name} {notify_resume} {notify_resume_pid} {notify_set_access} {notify_set_options} {notify_set_owner}
		{notify_set_state} {notify_simple_post} {notify_suspend} {notify_suspend_pid} {nrand48} {ntohl}
		{ntohs} {offtime} {open} {open$NOCANCEL$UNIX2003} {open$UNIX2003} {open_dprotected_np}
		{opendev} {opendir} {opendir$INODE64$UNIX2003} {opendir$UNIX2003} {openpty} {openx_np}
		{os_lock_lock} {os_lock_trylock} {os_lock_unlock} {panic} {panic_init} {pathconf}
		{pause} {pause$NOCANCEL$UNIX2003} {pause$UNIX2003} {pclose} {peeloff} {perror}
		{pid_for_task} {pid_resume} {pid_suspend} {pipe} {pmap_getmaps} {pmap_getport}
		{pmap_getport_timeout} {pmap_rmtcall} {pmap_set} {pmap_unset} {pmap_wakeup} {poll}
		{poll$NOCANCEL$UNIX2003} {poll$UNIX2003} {popen} {popen$DARWIN_EXTSN} {popen$UNIX2003} {port_obj_init}
		{posix2time} {posix_madvise} {posix_memalign} {posix_openpt} {posix_spawn} {posix_spawn_file_actions_addclose}
		{posix_spawn_file_actions_adddup2} {posix_spawn_file_actions_addinherit_np} {posix_spawn_file_actions_addopen} {posix_spawn_file_actions_destroy} {posix_spawn_file_actions_init} {posix_spawnattr_destroy}
		{posix_spawnattr_getbinpref_np} {posix_spawnattr_getcpumonitor} {posix_spawnattr_getflags} {posix_spawnattr_getmacpolicyinfo_np} {posix_spawnattr_getpcontrol_np} {posix_spawnattr_getpgroup}
		{posix_spawnattr_getprocesstype_np} {posix_spawnattr_getsigdefault} {posix_spawnattr_getsigmask} {posix_spawnattr_init} {posix_spawnattr_set_importancewatch_port_np} {posix_spawnattr_setauditsessionport_np}
		{posix_spawnattr_setbinpref_np} {posix_spawnattr_setcpumonitor} {posix_spawnattr_setcpumonitor_default} {posix_spawnattr_setexceptionports_np} {posix_spawnattr_setflags} {posix_spawnattr_setmacpolicyinfo_np}
		{posix_spawnattr_setpcontrol_np} {posix_spawnattr_setpgroup} {posix_spawnattr_setprocesstype_np} {posix_spawnattr_setsigdefault} {posix_spawnattr_setsigmask} {posix_spawnattr_setspecialport_np}
		{posix_spawnp} {pow} {pow$fenv_access_off} {powf} {powf$fenv_access_off} {powl}
		{powl$fenv_access_off} {prdb_end} {prdb_get} {prdb_getbyname} {prdb_set} {pread}
		{pread$NOCANCEL$UNIX2003} {pread$UNIX2003} {printf} {printf_l} {proc_clear_delayidlesleep} {proc_clear_vmpressure}
		{proc_disable_apptype} {proc_disable_cpumon} {proc_disable_wakemon} {proc_donate_importance_boost} {proc_enable_apptype} {proc_get_cpumon_params}
		{proc_get_dirty} {proc_get_wakemon_params} {proc_importance_assertion_begin_with_msg} {proc_importance_assertion_complete} {proc_kmsgbuf} {proc_libversion}
		{proc_listallpids} {proc_listchildpids} {proc_listpgrppids} {proc_listpids} {proc_listpidspath} {proc_name}
		{proc_pid_rusage} {proc_pidfdinfo} {proc_pidfileportinfo} {proc_pidinfo} {proc_pidpath} {proc_regionfilename}
		{proc_rlimit_control} {proc_set_cpumon_defaults} {proc_set_cpumon_params} {proc_set_delayidlesleep} {proc_set_dirty} {proc_set_owner_vmpressure}
		{proc_set_wakemon_defaults} {proc_set_wakemon_params} {proc_setpcontrol} {proc_suppress} {proc_terminate} {proc_track_dirty}
		{proc_uuid_policy} {processor_assign} {processor_control} {processor_exit} {processor_get_assignment} {processor_info}
		{processor_set_create} {processor_set_default} {processor_set_destroy} {processor_set_info} {processor_set_max_priority} {processor_set_policy_control}
		{processor_set_policy_disable} {processor_set_policy_enable} {processor_set_stack_usage} {processor_set_statistics} {processor_set_tasks} {processor_set_threads}
		{processor_start} {pselect} {pselect$DARWIN_EXTSN} {pselect$DARWIN_EXTSN$NOCANCEL} {pselect$NOCANCEL$UNIX2003} {pselect$UNIX2003}
		{psignal} {psort} {psort_b} {psort_r} {pthread_atfork} {pthread_attr_destroy}
		{pthread_attr_getdetachstate} {pthread_attr_getguardsize} {pthread_attr_getinheritsched} {pthread_attr_getschedparam} {pthread_attr_getschedpolicy} {pthread_attr_getscope}
		{pthread_attr_getstack} {pthread_attr_getstackaddr} {pthread_attr_getstacksize} {pthread_attr_init} {pthread_attr_setdetachstate} {pthread_attr_setguardsize}
		{pthread_attr_setinheritsched} {pthread_attr_setschedparam} {pthread_attr_setschedpolicy} {pthread_attr_setscope} {pthread_attr_setstack} {pthread_attr_setstackaddr}
		{pthread_attr_setstacksize} {pthread_cancel} {pthread_cancel$UNIX2003} {pthread_cond_broadcast} {pthread_cond_destroy} {pthread_cond_init}
		{pthread_cond_init$UNIX2003} {pthread_cond_signal} {pthread_cond_signal_thread_np} {pthread_cond_timedwait} {pthread_cond_timedwait$NOCANCEL$UNIX2003} {pthread_cond_timedwait$UNIX2003}
		{pthread_cond_timedwait_relative_np} {pthread_cond_wait} {pthread_cond_wait$NOCANCEL$UNIX2003} {pthread_cond_wait$UNIX2003} {pthread_condattr_destroy} {pthread_condattr_getpshared}
		{pthread_condattr_init} {pthread_condattr_setpshared} {pthread_create} {pthread_create_suspended_np} {pthread_detach} {pthread_equal}
		{pthread_exit} {pthread_from_mach_thread_np} {pthread_get_stackaddr_np} {pthread_get_stacksize_np} {pthread_getconcurrency} {pthread_getname_np}
		{pthread_getschedparam} {pthread_getspecific} {pthread_getugid_np} {pthread_introspection_hook_install} {pthread_is_threaded_np} {pthread_join}
		{pthread_join$NOCANCEL$UNIX2003} {pthread_join$UNIX2003} {pthread_key_create} {pthread_key_delete} {pthread_key_init_np} {pthread_kill}
		{pthread_mach_thread_np} {pthread_main_np} {pthread_main_thread_np} {pthread_mutex_destroy} {pthread_mutex_getprioceiling} {pthread_mutex_init}
		{pthread_mutex_lock} {pthread_mutex_setprioceiling} {pthread_mutex_trylock} {pthread_mutex_unlock} {pthread_mutexattr_destroy} {pthread_mutexattr_destroy$UNIX2003}
		{pthread_mutexattr_getprioceiling} {pthread_mutexattr_getprotocol} {pthread_mutexattr_getpshared} {pthread_mutexattr_gettype} {pthread_mutexattr_init} {pthread_mutexattr_setpolicy_np}
		{pthread_mutexattr_setprioceiling} {pthread_mutexattr_setprotocol} {pthread_mutexattr_setpshared} {pthread_mutexattr_settype} {pthread_once} {pthread_rwlock_destroy}
		{pthread_rwlock_destroy$UNIX2003} {pthread_rwlock_init} {pthread_rwlock_init$UNIX2003} {pthread_rwlock_rdlock} {pthread_rwlock_rdlock$UNIX2003} {pthread_rwlock_tryrdlock}
		{pthread_rwlock_tryrdlock$UNIX2003} {pthread_rwlock_trywrlock} {pthread_rwlock_trywrlock$UNIX2003} {pthread_rwlock_unlock} {pthread_rwlock_unlock$UNIX2003} {pthread_rwlock_wrlock}
		{pthread_rwlock_wrlock$UNIX2003} {pthread_rwlockattr_destroy} {pthread_rwlockattr_getpshared} {pthread_rwlockattr_init} {pthread_rwlockattr_setpshared} {pthread_self}
		{pthread_setcancelstate} {pthread_setcancelstate$UNIX2003} {pthread_setcanceltype} {pthread_setcanceltype$UNIX2003} {pthread_setconcurrency} {pthread_setname_np}
		{pthread_setschedparam} {pthread_setspecific} {pthread_setugid_np} {pthread_sigmask} {pthread_sigmask$UNIX2003} {pthread_testcancel}
		{pthread_testcancel$UNIX2003} {pthread_threadid_np} {pthread_workqueue_addthreads_np} {pthread_workqueue_setdispatch_np} {pthread_workqueue_setdispatchoffset_np} {pthread_yield_np}
		{ptrace} {ptsname} {put_rdata} {put_string} {put_uint16} {put_uint32}
		{putc} {putc_unlocked} {putchar} {putchar_unlocked} {putenv} {putenv$UNIX2003}
		{puts} {pututxline} {putw} {putwc} {putwc_l} {putwchar}
		{putwchar_l} {pwrite} {pwrite$NOCANCEL$UNIX2003} {pwrite$UNIX2003} {qsort} {qsort_b}
		{qsort_r} {querylocale} {quota} {quotactl} {radixsort} {raise}
		{rand} {rand_r} {random} {rb_tree_count} {rb_tree_find_node} {rb_tree_find_node_geq}
		{rb_tree_find_node_leq} {rb_tree_init} {rb_tree_insert_node} {rb_tree_iterate} {rb_tree_remove_node} {rcmd}
		{rcmd_af} {read} {read$NOCANCEL$UNIX2003} {read$UNIX2003} {readdir} {readdir$INODE64}
		{readdir_r} {readdir_r$INODE64} {readlink} {readpassphrase} {readv} {readv$NOCANCEL$UNIX2003}
		{readv$UNIX2003} {realloc} {reallocf} {realpath} {realpath$DARWIN_EXTSN} {realpath$UNIX2003}
		{reboot} {recv} {recv$NOCANCEL$UNIX2003} {recv$UNIX2003} {recvfrom} {recvfrom$NOCANCEL$UNIX2003}
		{recvfrom$UNIX2003} {recvmsg} {recvmsg$NOCANCEL$UNIX2003} {recvmsg$UNIX2003} {regcomp} {regcomp$UNIX2003}
		{regcomp_l} {regerror} {regexec} {regfree} {register_printf_domain_function} {register_printf_domain_render_std}
		{registerrpc} {regncomp} {regncomp_l} {regnexec} {regwcomp} {regwcomp_l}
		{regwexec} {regwncomp} {regwncomp_l} {regwnexec} {remainder} {remainder$fenv_access_off}
		{remainderf} {remainderf$fenv_access_off} {remainderl} {remainderl$fenv_access_off} {remove} {removexattr}
		{remque} {remquo} {remquo$fenv_access_off} {remquof} {remquof$fenv_access_off} {remquol}
		{remquol$fenv_access_off} {rename} {res_init} {res_query} {res_search} {revoke}
		{rewind} {rewinddir} {rewinddir$INODE64$UNIX2003} {rewinddir$UNIX2003} {rindex} {rint}
		{rint$fenv_access_off} {rintf} {rintf$fenv_access_off} {rintl} {rintl$fenv_access_off} {rinttol}
		{rmdir} {round} {round$fenv_access_off} {roundf} {roundf$fenv_access_off} {roundl}
		{roundl$fenv_access_off} {roundtol} {rresvport} {rresvport_af} {ruserok} {sbrk}
		{scalable_zone_info} {scalable_zone_statistics} {scalb} {scalbln} {scalbln$fenv_access_off} {scalblnf}
		{scalblnf$fenv_access_off} {scalblnl} {scalblnl$fenv_access_off} {scalbn} {scalbn$fenv_access_off} {scalbnf}
		{scalbnf$fenv_access_off} {scalbnl} {scalbnl$fenv_access_off} {scandir} {scandir$INODE64} {scandir_b}
		{scandir_b$INODE64} {scanf} {scanf_l} {sched_get_priority_max} {sched_get_priority_min} {sched_yield}
		{searchfs} {seed48} {seekdir} {seekdir$INODE64$UNIX2003} {seekdir$UNIX2003} {select}
		{select$DARWIN_EXTSN} {select$DARWIN_EXTSN$NOCANCEL} {select$NOCANCEL$UNIX2003} {select$UNIX2003} {sem_close} {sem_destroy}
		{sem_getvalue} {sem_init} {sem_open} {sem_post} {sem_trywait} {sem_unlink}
		{sem_wait} {sem_wait$NOCANCEL$UNIX2003} {sem_wait$UNIX2003} {semaphore_create} {semaphore_destroy} {semaphore_signal}
		{semaphore_signal_all} {semaphore_signal_all_trap} {semaphore_signal_thread} {semaphore_signal_thread_trap} {semaphore_signal_trap} {semaphore_timedwait}
		{semaphore_timedwait_signal} {semaphore_timedwait_signal_trap} {semaphore_timedwait_trap} {semaphore_wait} {semaphore_wait_signal} {semaphore_wait_signal_trap}
		{semaphore_wait_trap} {semctl} {semctl$UNIX2003} {semget} {semop} {semsys}
		{send} {send$NOCANCEL$UNIX2003} {send$UNIX2003} {sendfile} {sendmsg} {sendmsg$NOCANCEL$UNIX2003}
		{sendmsg$UNIX2003} {sendto} {sendto$NOCANCEL$UNIX2003} {sendto$UNIX2003} {set_dp_control_port} {set_malloc_singlethreaded}
		{set_rpc_maxgrouplist} {setattrlist} {setattrlist$UNIX2003} {setaudit} {setaudit_addr} {setauid}
		{setbuf} {setbuffer} {setcontext} {setdomainname} {setegid} {setenv}
		{setenv$UNIX2003} {seteuid} {setfsent} {setgid} {setgrent} {setgroupent}
		{setgroups} {sethostent} {sethostid} {sethostname} {setinvalidrune} {setiopolicy_np}
		{setipv4sourcefilter} {setitimer} {setjmp} {setkey} {setkey$UNIX2003} {setlinebuf}
		{setlocale} {setlogin} {setmode} {setmode$UNIX2003} {setnetent} {setnetgrent}
		{setpassent} {setpgid} {setpgrp} {setpgrp$UNIX2003} {setpriority} {setprivexec}
		{setprogname} {setprotoent} {setpwent} {setquota} {setregid} {setregid$UNIX2003}
		{setreuid} {setreuid$UNIX2003} {setrgid} {setrlimit} {setrlimit$UNIX2003} {setrpcent}
		{setruid} {setrunelocale} {setservent} {setsgroups_np} {setsid} {setsockopt}
		{setsourcefilter} {setstate} {settimeofday} {setttyent} {setuid} {setusershell}
		{setutxent} {setutxent_wtmp} {setvbuf} {setwgroups_np} {setxattr} {shm_open}
		{shm_unlink} {shmat} {shmctl} {shmctl$UNIX2003} {shmdt} {shmget}
		{shmsys} {shutdown} {si_addrinfo} {si_addrinfo_list} {si_addrinfo_list_from_hostent} {si_addrinfo_v4}
		{si_addrinfo_v4_mapped} {si_addrinfo_v6} {si_alias_all} {si_alias_byname} {si_async_call} {si_async_cancel}
		{si_async_handle_reply} {si_cache_add_item} {si_cache_add_list} {si_fs_all} {si_fs_byfile} {si_fs_byspec}
		{si_group_all} {si_group_bygid} {si_group_byname} {si_group_byuuid} {si_grouplist} {si_host_all}
		{si_host_byaddr} {si_host_byname} {si_in_netgroup} {si_ipnode_byname} {si_item_call} {si_item_is_valid}
		{si_item_match} {si_item_release} {si_item_retain} {si_list_add} {si_list_call} {si_list_concat}
		{si_list_next} {si_list_release} {si_list_reset} {si_list_retain} {si_list_to_addrinfo} {si_mac_all}
		{si_mac_bymac} {si_mac_byname} {si_module_name} {si_module_release} {si_module_retain} {si_module_static_cache}
		{si_module_static_ds} {si_module_static_file} {si_module_static_mdns} {si_module_static_search} {si_module_vers} {si_module_with_name}
		{si_module_with_path} {si_nameinfo} {si_netgroup_byname} {si_network_all} {si_network_byaddr} {si_network_byname}
		{si_protocol_all} {si_protocol_byname} {si_protocol_bynumber} {si_rpc_all} {si_rpc_byname} {si_rpc_bynumber}
		{si_search} {si_search_module_set_flags} {si_service_all} {si_service_byname} {si_service_byport} {si_srv_byname}
		{si_standardize_mac_address} {si_user_all} {si_user_byname} {si_user_byuid} {si_user_byuuid} {si_wants_addrinfo}
		{sigaction} {sigaddset} {sigaltstack} {sigaltstack$UNIX2003} {sigblock} {sigdelset}
		{sigemptyset} {sigfillset} {sighold} {sigignore} {siginterrupt} {sigismember}
		{siglongjmp} {signal} {significand} {sigpause} {sigpause$NOCANCEL$UNIX2003} {sigpause$UNIX2003}
		{sigpending} {sigprocmask} {sigrelse} {sigset} {sigsetjmp} {sigsetmask}
		{sigsuspend} {sigsuspend$NOCANCEL$UNIX2003} {sigsuspend$UNIX2003} {sigvec} {sigwait} {sigwait$NOCANCEL$UNIX2003}
		{sigwait$UNIX2003} {sin} {sin$fenv_access_off} {sinf} {sinf$fenv_access_off} {sinh}
		{sinh$fenv_access_off} {sinhf} {sinhf$fenv_access_off} {sinhl} {sinhl$fenv_access_off} {sinl}
		{sinl$fenv_access_off} {sl_add} {sl_find} {sl_free} {sl_init} {sleep}
		{sleep$NOCANCEL$UNIX2003} {sleep$UNIX2003} {snprintf} {snprintf_l} {sockatmark} {socket}
		{socket_delegate} {socketpair} {socketpair$UNIX2003} {spin_lock} {spin_lock_try} {spin_unlock}
		{sprintf} {sprintf_l} {sqrt} {sqrt$fenv_access_off} {sqrtf} {sqrtf$fenv_access_off}
		{sqrtl} {sqrtl$fenv_access_off} {sradixsort} {srand} {srand48} {sranddev}
		{srandom} {srandomdev} {sscanf} {sscanf_l} {stack_logging_enumerate_records} {stack_logging_frames_for_uniqued_stack}
		{stack_logging_get_frames} {stack_logging_log_stack} {start_wqthread} {stat} {stat$INODE64} {stat64}
		{statfs} {statfs$INODE64} {statfs64} {statvfs} {statx64_np} {statx_np}
		{statx_np$INODE64} {stpcpy} {stpncpy} {strcasecmp} {strcasecmp_l} {strcasestr}
		{strcasestr_l} {strcat} {strcoll} {strcoll_l} {strcpy} {strcspn}
		{strdup} {strerror} {strerror$UNIX2003} {strerror_r} {strfmon} {strfmon_l}
		{strftime} {strftime$UNIX2003} {strftime_l} {strftime_l$UNIX2003} {strlcat} {strlcpy}
		{strlen} {strmode} {strncasecmp} {strncasecmp_l} {strncat} {strncpy}
		{strndup} {strnlen} {strnstr} {strpbrk} {strptime} {strptime$UNIX2003}
		{strptime_l} {strptime_l$UNIX2003} {strrchr} {strsep} {strsignal} {strspn}
		{strstr} {strtod} {strtod$UNIX2003} {strtod_l} {strtod_l$UNIX2003} {strtof}
		{strtof$UNIX2003} {strtof_l} {strtof_l$UNIX2003} {strtofflags} {strtoimax} {strtoimax_l}
		{strtok} {strtok_r} {strtol} {strtol_l} {strtold} {strtold_l}
		{strtoll} {strtoll_l} {strtoq} {strtoq_l} {strtoul} {strtoul_l}
		{strtoull} {strtoull_l} {strtoumax} {strtoumax_l} {strtouq} {strtouq_l}
		{strunvis} {strunvisx} {strvis} {strvisx} {strxfrm} {strxfrm_l}
		{svc_getreq} {svc_getreqset} {svc_register} {svc_run} {svc_sendreply} {svc_unregister}
		{svcerr_auth} {svcerr_decode} {svcerr_noproc} {svcerr_noprog} {svcerr_progvers} {svcerr_systemerr}
		{svcerr_weakauth} {svcfd_create} {svcraw_create} {svctcp_create} {svcudp_bufcreate} {svcudp_create}
		{svcudp_enablecache} {swab} {swapcontext} {swapon} {swprintf} {swprintf_l}
		{swscanf} {swscanf_l} {swtch} {swtch_pri} {sxprintf} {sxprintf_exec}
		{symlink} {sync} {sync_volume_np} {sys_cache_control} {sys_dcache_flush} {sys_icache_invalidate}
		{syscall} {syscall_thread_switch} {sysconf} {sysctl} {sysctlbyname} {sysctlnametomib}
		{system} {system$NOCANCEL$UNIX2003} {system$UNIX2003} {system_override} {tan} {tan$fenv_access_off}
		{tanf} {tanf$fenv_access_off} {tanh} {tanh$fenv_access_off} {tanhf} {tanhf$fenv_access_off}
		{tanhl} {tanhl$fenv_access_off} {tanl} {tanl$fenv_access_off} {task_assign} {task_assign_default}
		{task_create} {task_for_pid} {task_get_assignment} {task_get_emulation_vector} {task_get_exception_ports} {task_get_special_port}
		{task_get_state} {task_info} {task_name_for_pid} {task_policy} {task_policy_get} {task_policy_set}
		{task_purgable_info} {task_resume} {task_resume2} {task_sample} {task_self_} {task_self_trap}
		{task_set_emulation} {task_set_emulation_vector} {task_set_exception_ports} {task_set_info} {task_set_phys_footprint_limit} {task_set_policy}
		{task_set_port_space} {task_set_ras_pc} {task_set_special_port} {task_set_state} {task_suspend} {task_suspend2}
		{task_swap_exception_ports} {task_terminate} {task_threads} {task_wire} {task_zone_info} {tcdrain}
		{tcdrain$NOCANCEL$UNIX2003} {tcdrain$UNIX2003} {tcflow} {tcflush} {tcgetattr} {tcgetpgrp}
		{tcgetsid} {tcsendbreak} {tcsetattr} {tcsetpgrp} {tdelete} {telldir}
		{telldir$INODE64$UNIX2003} {telldir$UNIX2003} {tempnam} {tempnam$UNIX2003} {tfind} {tgamma}
		{tgamma$fenv_access_off} {tgammaf} {tgammaf$fenv_access_off} {tgammal} {tgammal$fenv_access_off} {thread_abort}
		{thread_abort_safely} {thread_assign} {thread_assign_default} {thread_create} {thread_create_running} {thread_depress_abort}
		{thread_get_assignment} {thread_get_exception_ports} {thread_get_special_port} {thread_get_state} {thread_info} {thread_policy}
		{thread_policy_get} {thread_policy_set} {thread_resume} {thread_sample} {thread_self_trap} {thread_set_exception_ports}
		{thread_set_policy} {thread_set_special_port} {thread_set_state} {thread_stack_pcs} {thread_start} {thread_suspend}
		{thread_swap_exception_ports} {thread_switch} {thread_terminate} {thread_wire} {time} {time2posix}
		{timegm} {timelocal} {timeoff} {times} {timezone} {tmpfile}
		{tmpnam} {toascii} {tolower} {tolower_l} {toupper} {toupper_l}
		{towctrans} {towctrans_l} {towlower} {towlower_l} {towupper} {towupper_l}
		{trunc} {trunc$fenv_access_off} {truncate} {truncf} {truncf$fenv_access_off} {truncl}
		{truncl$fenv_access_off} {tsearch} {ttyname} {ttyname_r} {ttyname_r$UNIX2003} {ttyslot}
		{twalk} {tzset} {tzsetwall} {ualarm} {ulimit} {umask}
		{umaskx_np} {uname} {undelete} {ungetc} {ungetwc} {ungetwc_l}
		{unlink} {unlockpt} {unmount} {unsetenv} {unsetenv$UNIX2003} {unvis}
		{unw_get_fpreg} {unw_get_proc_info} {unw_get_proc_name} {unw_get_reg} {unw_getcontext} {unw_init_local}
		{unw_is_fpreg} {unw_is_signal_frame} {unw_iterate_dwarf_unwind_cache} {unw_regname} {unw_resume} {unw_set_fpreg}
		{unw_set_reg} {unw_step} {uselocale} {user_from_uid} {usleep} {usleep$NOCANCEL$UNIX2003}
		{usleep$UNIX2003} {utime} {utimes} {utmpxname} {uuid_clear} {uuid_compare}
		{uuid_copy} {uuid_generate} {uuid_generate_random} {uuid_generate_time} {uuid_is_null} {uuid_pack}
		{uuid_parse} {uuid_unpack} {uuid_unparse} {uuid_unparse_lower} {uuid_unparse_upper} {valloc}
		{vasprintf} {vasprintf_l} {vasxprintf} {vasxprintf_exec} {vdprintf} {vdprintf_l}
		{vdxprintf} {vdxprintf_exec} {verr} {verrc} {verrx} {vfork}
		{vfprintf} {vfprintf_l} {vfree} {vfs_purge} {vfscanf} {vfscanf_l}
		{vfwprintf} {vfwprintf_l} {vfwscanf} {vfwscanf_l} {vfxprintf} {vfxprintf_exec}
		{vis} {vm_allocate} {vm_allocate_cpm} {vm_behavior_set} {vm_copy} {vm_deallocate}
		{vm_inherit} {vm_machine_attribute} {vm_map} {vm_map_64} {vm_map_page_query} {vm_mapped_pages_info}
		{vm_msync} {vm_pressure_monitor} {vm_protect} {vm_purgable_control} {vm_read} {vm_read_list}
		{vm_read_overwrite} {vm_region} {vm_region_64} {vm_region_recurse} {vm_region_recurse_64} {vm_remap}
		{vm_wire} {vm_write} {vprintf} {vprintf_l} {vscanf} {vscanf_l}
		{vsnprintf} {vsnprintf_l} {vsprintf} {vsprintf_l} {vsscanf} {vsscanf_l}
		{vswprintf} {vswprintf_l} {vswscanf} {vswscanf_l} {vsxprintf} {vsxprintf_exec}
		{vwarn} {vwarnc} {vwarnx} {vwprintf} {vwprintf_l} {vwscanf}
		{vwscanf_l} {vxprintf} {vxprintf_exec} {wait} {wait$NOCANCEL$UNIX2003} {wait$UNIX2003}
		{wait3} {wait4} {waitevent} {waitid} {waitid$NOCANCEL$UNIX2003} {waitid$UNIX2003}
		{waitpid} {waitpid$NOCANCEL$UNIX2003} {waitpid$UNIX2003} {warn} {warnc} {warnx}
		{watchevent} {wcpcpy} {wcpncpy} {wcrtomb} {wcrtomb_l} {wcscasecmp}
		{wcscasecmp_l} {wcscat} {wcschr} {wcscmp} {wcscoll} {wcscoll_l}
		{wcscpy} {wcscspn} {wcsdup} {wcsftime} {wcsftime$UNIX2003} {wcsftime_l}
		{wcsftime_l$UNIX2003} {wcslcat} {wcslcpy} {wcslen} {wcsncasecmp} {wcsncasecmp_l}
		{wcsncat} {wcsncmp} {wcsncpy} {wcsnlen} {wcsnrtombs} {wcsnrtombs_l}
		{wcspbrk} {wcsrchr} {wcsrtombs} {wcsrtombs_l} {wcsspn} {wcsstr}
		{wcstod} {wcstod_l} {wcstof} {wcstof_l} {wcstoimax} {wcstoimax_l}
		{wcstok} {wcstol} {wcstol_l} {wcstold} {wcstold_l} {wcstoll}
		{wcstoll_l} {wcstombs} {wcstombs_l} {wcstoul} {wcstoul_l} {wcstoull}
		{wcstoull_l} {wcstoumax} {wcstoumax_l} {wcswidth} {wcswidth_l} {wcsxfrm}
		{wcsxfrm_l} {wctob} {wctob_l} {wctomb} {wctomb_l} {wctrans}
		{wctrans_l} {wctype} {wctype_l} {wcwidth} {wcwidth_l} {wmemchr}
		{wmemcmp} {wmemcpy} {wmemmove} {wmemset} {wordexp} {wordfree}
		{wprintf} {wprintf_l} {write} {write$NOCANCEL$UNIX2003} {write$UNIX2003} {writev}
		{writev$NOCANCEL$UNIX2003} {writev$UNIX2003} {wscanf} {wscanf_l} {wtmpxname} {xdr_accepted_reply}
		{xdr_array} {xdr_authunix_parms} {xdr_bool} {xdr_bytes} {xdr_callhdr} {xdr_callmsg}
		{xdr_char} {xdr_des_block} {xdr_domainname} {xdr_double} {xdr_enum} {xdr_float}
		{xdr_free} {xdr_hyper} {xdr_int} {xdr_int16_t} {xdr_int32_t} {xdr_int64_t}
		{xdr_keydat} {xdr_long} {xdr_longlong_t} {xdr_mapname} {xdr_netobj} {xdr_opaque}
		{xdr_opaque_auth} {xdr_peername} {xdr_pmap} {xdr_pmaplist} {xdr_pointer} {xdr_reference}
		{xdr_rejected_reply} {xdr_replymsg} {xdr_rmtcall_args} {xdr_rmtcallres} {xdr_short} {xdr_sizeof}
		{xdr_string} {xdr_u_char} {xdr_u_hyper} {xdr_u_int} {xdr_u_int16_t} {xdr_u_int32_t}
		{xdr_u_int64_t} {xdr_u_long} {xdr_u_longlong_t} {xdr_u_short} {xdr_union} {xdr_valdat}
		{xdr_vector} {xdr_void} {xdr_wrapstring} {xdr_x_passwd} {xdr_ypbind_binding} {xdr_ypbind_resp}
		{xdr_ypbind_resptype} {xdr_ypbind_setdom} {xdr_ypmaplist} {xdr_yppasswd} {xdr_ypreq_key} {xdr_ypreq_nokey}
		{xdr_ypresp_all} {xdr_ypresp_all_seq} {xdr_ypresp_key_val} {xdr_ypresp_maplist} {xdr_ypresp_master} {xdr_ypresp_order}
		{xdr_ypresp_val} {xdr_ypstat} {xdrmem_create} {xdrrec_create} {xdrrec_endofrecord} {xdrrec_eof}
		{xdrrec_skiprecord} {xdrstdio_create} {xprintf} {xprintf_exec} {xprt_register} {xprt_unregister}
		{y0} {y1} {yn} {yp_all} {yp_bind} {yp_first}
		{yp_get_default_domain} {yp_maplist} {yp_master} {yp_match} {yp_next} {yp_order}
		{yp_unbind} {yperr_string} {ypprot_err} {zeroify_scalable_zone}
	]
	variables: [
		{NDR_record} {NETGROUP} {_CurrentRuneLocale} {__check_rhosts_file} {__collate_load_error} {__default_hash}
		{__in_sigtramp} {__mb_cur_max} {__mb_sb_limit} {__sF} {__sglue} {__stderrp}
		{__stdinp} {__stdoutp} {_cthread_init_routine} {_rand48_add} {_rand48_mult} {_rand48_seed}
		{_yplib_cache} {_yplib_timeout} {gL1CacheEnabled} {important_boost_assertion_token} {malloc_check_each} {non_boost_assertion_token}
		{normal_boost_assertion_token} {opterr} {optind} {port_obj_table_size} {svc_maxfd} {szone_check_modulo}
		{tzname} {vm_kernel_page_mask} {vm_kernel_page_shift} {vm_kernel_page_size} {vm_page_mask} {vm_page_shift}
		{vm_page_size} {VersionString_SCCS_libdnssd} {_DefaultRuneLocale} {_FE_DFL_DISABLE_SSE_DENORMS_ENV} {_FE_DFL_ENV} {_NSConcreteAutoBlock}
		{_NSConcreteFinalizingBlock} {_NSConcreteGlobalBlock} {_NSConcreteMallocBlock} {_NSConcreteStackBlock} {_NSConcreteWeakBlockVariable} {_PathLocale}
		{__Libm_version} {___kernelVersionNumber} {___kernelVersionString} {__bigtens_D2A} {__cVersionNumber} {__cVersionString}
		{__cleanup} {__gdtoa_locks} {__hexdig_D2A} {__is_threaded} {__kernelVersionNumber} {__kernelVersionString}
		{__keymgr_global} {__libsystem_mallocVersionNumber} {__libsystem_mallocVersionString} {__libsystem_notifyVersionNumber} {__libsystem_notifyVersionString} {__rcmd_errstr}
		{__sdidinit} {__stack_chk_guard} {__stack_log_file_path__} {__syscall_logger} {__system_pthreadVersionNumber} {__system_pthreadVersionString}
		{__tens_D2A} {__tinytens_D2A} {__unix_conforming} {_c_locale} {_cpu_capabilities} {_cpu_has_altivec}
		{_ds_port} {_mach_errors} {_malloc_no_asl_log} {_null_auth} {_os_alloc_once_table} {_os_lock_type_eliding}
		{_os_lock_type_handoff} {_os_lock_type_spin} {_os_lock_type_transactional} {_proto_stayopen} {_res} {_si_opendirectory_disabled}
		{_sigintr} {_yp_domain} {_ypbindlist} {bootstrap_port} {clock_port} {clock_sem}
		{daylight} {errno} {getdate_err} {h_errlist} {h_errno} {h_nerr}
		{in6addr_any} {in6addr_linklocal_allnodes} {in6addr_linklocal_allrouters} {in6addr_loopback} {in6addr_nodelocal_allnodes} {internal_DNSServiceDiscoveryReply_subsystem}
		{internal_catch_exc_subsystem} {keymgrVersionNumber} {keymgrVersionString} {mach_error_full_diag} {mach_host_self_} {mach_task_self_}
		{malloc_check_counter} {malloc_check_start} {malloc_debug_flags} {malloc_logger} {malloc_num_zones} {malloc_num_zones_allocated}
		{malloc_zones} {optarg} {optopt} {optreset} {pl} {port_obj_table}
		{rpc_createerr} {rpcdata} {signgam} {stack_logging_dontcompact} {stack_logging_enable_logging} {stack_logging_finished_init}
		{stack_logging_postponed} {stack_logging_the_record_list} {suboptarg} {svc_fdset} {sys_errlist} {sys_nerr}
		{sys_siglist} {sys_signame} {system_blocksVersionNumber} {system_blocksVersionString} {szone_check_counter} {szone_check_start}
		{timezone$UNIX2003} {vers} {vprintf_stderr_func} {ypresp_allfn} {ypresp_data}
	]
]
