Red/System [
	Title:   "Red/System auto-generated float! tests"
	Author:  "Peter W A Wood"
	File: 	 %dylib-auto-test.reds
	License: "BSD-3 - https://github.com/dockimbel/Red/blob/origin/BSD-3-License.txt"
]

;;	This file is generated by make-dylib-auto-test.r
;;	Do not edit this file directly.

;make-length:657 

#include %../../../../../quick-test/quick-test.reds

~~~start-file~~~ "Auto-generated dylib tests"

#import [
	"libtest-dll1.dll" cdecl [
    	dll1-add-one: "add-one" [
        	i       		[integer!]
        	return: 		[integer!]
        ]
    ]
    "libtest-dll2.dll" cdecl [
  	    dll2-negate: "neg" [
  		    i				[integer!]
  		    return:			[integer!]
  	    ]
  	    dll2-negatef: "negf" [
  		    f				[float!]
  		    return:			[float!]
  	    ]
  	    dll2-negatef32: "negf32" [
  			f32				[float32!]
  			return:	   		[float32!]
  		]
  		dll2-true-false: "true-false" [
  			l				[logic!]
  			return:			[logic!]
  		]
  		dll2-odd-or-even: "odd-or-even" [
  			s				[c-string!]
  			return:			[c-string!]
  		]
  		;dll2-callbacki: "callbacki" [
  		;	i				[integer!]
  		;	f				[function! [i [integer!]]]
  		;]
    ]	
]

===start-group=== "One function exported"

	--test-- "dllf1"
	--assert 2 = dll1-add-one 1
  
	--test-- "dllf2"    
	--assert -2147483647 = dll1-add-one -2147483648
  
	--test-- "dllf3"
	--assert -2147483648 = dll1-add-one 2147483647

===end-group===

===start-group=== "Multi function export"

	--test-- "mfe1"
	--assert -1 = dll2-negate 1
	
	--test-- "mfe2"
	--assert -1.0 = dll2-negatef 1.0
	
	--test-- "mfe3"
	--assert (as float32! -1.0) = dll2-negatef32 (as float32! 1.0)
	
	--test-- "mfe4"
	--assert false = dll2-true-false true
	
	--test-- "mfe5"
	;--assert "odd" = dll2-odd-or-even "Hello"
	
===end-group===

;===start-group=== "Simple callback"
;	
;	--test-- "sc1"
;		sc1-i: 0
;		sc1-f: function [[cdecl] i [integer!]][sc1-i: i]
;	--assert 1 = dll2-callbacki 1 :sc1-f
;	
;===end-group=== 
~~~end-file~~~
